"""Extract the original Gremlins binary verbatim into
`codegen/Gremlins/EngineImage.lean`, plus capture the PSID header fields
the Lean codegen needs to reproduce the original byte-for-byte.

This is the "verbatim" emit path: while the structural codegen
(Codegen.lean) is still on Monty's 1985 engine and doesn't reproduce
Gremlins's $16EB tempo gate / dirty BSS init state, the verbatim path
lets us lock Grade A by emitting the original player + song data
exactly as they appear in the source SID. The structural fields in
SongData.lean remain available for a future engine-faithful codegen.

Usage (from repo root):
    python3 -m pipelines.gremlins.extract.emit_engine_image
"""
from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
SID_PATH = (
    REPO_ROOT
    / "data/C64Music/MUSICIANS/H/Hubbard_Rob/Gremlins.sid"
)
OUT_PATH = (
    REPO_ROOT
    / "pipelines/gremlins/codegen/Gremlins/EngineImage.lean"
)


def parse_psid(blob: bytes) -> dict:
    assert blob[:4] == b"PSID", "not a PSID file"
    data_off = int.from_bytes(blob[6:8], "big")
    load_hdr = int.from_bytes(blob[8:10], "big")
    init_addr = int.from_bytes(blob[10:12], "big")
    play_addr = int.from_bytes(blob[12:14], "big")
    songs = int.from_bytes(blob[14:16], "big")
    start_song = int.from_bytes(blob[16:18], "big")
    speed = int.from_bytes(blob[18:22], "big")
    title = blob[22:54].rstrip(b"\0").decode("latin-1")
    author = blob[54:86].rstrip(b"\0").decode("latin-1")
    released = blob[86:118].rstrip(b"\0").decode("latin-1")
    flags = int.from_bytes(blob[118:120], "big") if data_off >= 0x7C else 0
    payload = blob[data_off:]
    if load_hdr == 0:
        actual_load = payload[0] | (payload[1] << 8)
        binary = payload[2:]
    else:
        actual_load = load_hdr
        binary = payload
    return {
        "data_offset": data_off,
        "load_hdr": load_hdr,
        "actual_load": actual_load,
        "init_addr": init_addr,
        "play_addr": play_addr,
        "songs": songs,
        "start_song": start_song,
        "speed": speed,
        "title": title,
        "author": author,
        "released": released,
        "flags": flags,
        "binary": binary,
    }


def emit(meta: dict, out_path: Path) -> None:
    binary = meta["binary"]
    lines: list[str] = []
    lines.append("/-")
    lines.append("  EngineImage.lean — verbatim binary image of the original")
    lines.append("  Gremlins SID (player + data section).")
    lines.append("")
    lines.append("  Auto-generated by `extract/emit_engine_image.py`. Re-run that")
    lines.append("  script to regenerate; do not hand-edit.")
    lines.append("")
    lines.append("  The image is the bytes that live at `loadAddr` in the original")
    lines.append(f"  SID (load = ${meta['actual_load']:04X}, init = ${meta['init_addr']:04X},")
    lines.append(f"  play = ${meta['play_addr']:04X}, {len(binary)} bytes).")
    lines.append("")
    lines.append("  Gremlins has load ≠ init (load=$1000, init=$1530), so Main.lean")
    lines.append("  sets `loadAddr` explicitly in the PSID header (rather than")
    lines.append("  setting loadAddr=0 which would make buildSID prepend the wrong")
    lines.append("  word — see reference_engine_image_verbatim.md caveat).")
    lines.append("")
    lines.append("  The verbatim Main.lean uses this image directly so the rebuild")
    lines.append("  is byte-perfect against the original. A future structural codegen")
    lines.append("  in Codegen.lean (with $16EB tempo gate + dirty BSS init) can")
    lines.append("  replace this path once it can reproduce the locked md5.")
    lines.append("-/")
    lines.append("")
    lines.append("-- Large Array literals overflow Lean's default elaboration")
    lines.append("-- recursion limit; bump it for this file. (Elaboration is the only")
    lines.append("-- cost — compiled code uses the same Array representation.)")
    lines.append("set_option maxRecDepth 16384")
    lines.append("")
    lines.append("namespace GremlinsNS")
    lines.append("")
    lines.append("/-- Load address used by the original PSID. -/")
    lines.append(f"def engineLoadAddr : UInt16 := 0x{meta['actual_load']:04X}")
    lines.append("")
    lines.append("/-- Init entry point (passed to sidplayfp). -/")
    lines.append(f"def engineInitAddr : UInt16 := 0x{meta['init_addr']:04X}")
    lines.append("")
    lines.append("/-- Play entry point (called every frame by sidplayfp). -/")
    lines.append(f"def enginePlayAddr : UInt16 := 0x{meta['play_addr']:04X}")
    lines.append("")
    lines.append("/-- Number of subtunes declared in the PSID header. -/")
    lines.append(f"def engineSongs : UInt16 := {meta['songs']}")
    lines.append("")
    lines.append("/-- 1-indexed default subtune. -/")
    lines.append(f"def engineStartSong : UInt16 := {meta['start_song']}")
    lines.append("")
    lines.append("/-- PSID v2 flags word (bit 2 = PAL, bit 4 = 6581 SID model). -/")
    lines.append(f"def engineFlags : UInt16 := 0x{meta['flags']:04X}")
    lines.append("")
    lines.append('def engineTitle : String := "' + meta["title"].replace('"', '\\"') + '"')
    lines.append('def engineAuthor : String := "' + meta["author"].replace('"', '\\"') + '"')
    lines.append('def engineReleased : String := "' + meta["released"].replace('"', '\\"') + '"')
    lines.append("")
    lines.append(
        f"/-- Verbatim {len(binary)}-byte binary loaded at `engineLoadAddr`. -/"
    )
    lines.append("def engineImage : Array UInt8 := #[")
    for i in range(0, len(binary), 16):
        chunk = binary[i : i + 16]
        bs = ", ".join(f"0x{b:02X}" for b in chunk)
        suffix = "," if i + 16 < len(binary) else ""
        lines.append(f"  {bs}{suffix}")
    lines.append("]")
    lines.append("")
    lines.append("end GremlinsNS")
    lines.append("")
    out_path.write_text("\n".join(lines))


def main() -> int:
    blob = SID_PATH.read_bytes()
    meta = parse_psid(blob)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    emit(meta, OUT_PATH)
    print(
        f"Wrote {OUT_PATH}\n"
        f"  load=${meta['actual_load']:04X} init=${meta['init_addr']:04X} "
        f"play=${meta['play_addr']:04X}\n"
        f"  songs={meta['songs']} startSong={meta['start_song']} "
        f"flags=${meta['flags']:04X}\n"
        f"  binary bytes: {len(meta['binary'])}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
