version: 2
engine: battle_of_britain

psid {
  title:      "Battle of Britain"
  author:     "Rob Hubbard"
  released:   "1985 Personal Software Services"
  clock:      PAL
  sid:        6581
  start_song: 1
  speed:      $00000001
}

params {
  arp_interval: 12
  arp_period: 2
  arp_phase_invert: false
  first_frame_gate_off: false
  frame_ctr_init: 220
  freeze_on_stop: false
  has_incby2_late_gate: false
  has_stop_fill: false
  incby2_every_frame: false
  incby2_late_gate: -1
  incby2_onset: $03
  incby2_step: 2
  linear_pw_or: $00
  seed_overlap: true
  speed_ctr_init: 0
  stop_fill: $00
  suppress_first_notestart: false
  vib_onset: 6
}

init {
  voice 1 { ctrl: $41  dur_field: $1F  pwm_period: $00  pwm_dir: down  instr: i10  slide_v: $1D }
  voice 2 { ctrl: $41  dur_field: $1F  pwm_period: $00  pwm_dir: up  instr: i11  slide_v: $07 }
  voice 3 { ctrl: $41  dur_field: $03  pwm_period: $01  pwm_dir: up  instr: i3  slide_v: $D0 }
}

instrument 1 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=16 init=$0359 min_hi=8 max_hi=14
  adsr:     $58 $52
  arp:      offsets=[0] period=2
  vibrato:  scale=3
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 2 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=16 init=$0248 min_hi=8 max_hi=14
  adsr:     $58 $62
  arp:      offsets=[0] period=2
  vibrato:  scale=4
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 3 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=17 init=$0322 min_hi=8 max_hi=14
  adsr:     $0A $00
  arp:      offsets=[0] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 4 {
  waveform: $81
  loop:     0
  pwm:      mode=none speed=0 init=$0200 min_hi=0 max_hi=0
  adsr:     $0C $0A
  arp:      offsets=[0, 12] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 5 {
  waveform: $11
  loop:     0
  pwm:      mode=none speed=0 init=$0000 min_hi=0 max_hi=0
  adsr:     $0F $F0
  arp:      offsets=[0] period=2
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       inc_by2
}

instrument 6 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $58 $00
  arp:      offsets=[0, 12] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 7 {
  waveform: $41
  loop:     0
  pwm:      mode=bidirectional speed=129 init=$0C80 min_hi=8 max_hi=14
  adsr:     $57 $00
  arp:      offsets=[0] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 8 {
  waveform: $41
  loop:     0
  pwm:      mode=bidirectional speed=129 init=$0A80 min_hi=8 max_hi=14
  adsr:     $57 $00
  arp:      offsets=[0] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 9 {
  waveform: $41
  loop:     0
  pwm:      mode=bidirectional speed=225 init=$0AA0 min_hi=8 max_hi=14
  adsr:     $0F $FF
  arp:      offsets=[0] period=2
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 10 {
  waveform: $41
  loop:     0
  pwm:      mode=bidirectional speed=129 init=$0980 min_hi=8 max_hi=14
  adsr:     $00 $70
  arp:      offsets=[0] period=2
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 11 {
  waveform: $41
  loop:     0
  pwm:      mode=bidirectional speed=65 init=$0CC0 min_hi=8 max_hi=14
  adsr:     $00 $70
  arp:      offsets=[0] period=2
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 12 {
  waveform: $81
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $0B $D8
  arp:      offsets=[0, 12] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 13 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $09 $09
  arp:      offsets=[0] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 14 {
  waveform: $81
  loop:     0
  pwm:      mode=none speed=0 init=$0200 min_hi=0 max_hi=0
  adsr:     $0F $DF
  arp:      offsets=[0] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 15 {
  waveform: $41
  loop:     0
  pwm:      mode=bidirectional speed=225 init=$0DE0 min_hi=8 max_hi=14
  adsr:     $00 $FF
  arp:      offsets=[0] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 16 {
  waveform: $41
  loop:     0
  pwm:      mode=bidirectional speed=225 init=$0980 min_hi=8 max_hi=14
  adsr:     $00 $FF
  arp:      offsets=[0] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 17 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0380 min_hi=0 max_hi=0
  adsr:     $48 $60
  arp:      offsets=[0, 12] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 18 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0180 min_hi=0 max_hi=0
  adsr:     $09 $60
  arp:      offsets=[0, 12] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 19 {
  waveform: $11
  loop:     0
  pwm:      mode=none speed=0 init=$0000 min_hi=0 max_hi=0
  adsr:     $0F $FF
  arp:      offsets=[0] period=2
  vibrato:  scale=1
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       inc_by2
}

subtune 0 music {
  tempo: 2
  voice 1 {
    orderlist: 0 22 0 24 4 10 12 4 8 15 26 26 27 26 26 28 32 32 33 32 32 34 35 35 10 12 4 40 40 0 0 0 0 loop@0
    pattern 0 length=64 {
      C-0   32  tie
      C-0   32  tie
    }
    pattern 4 length=512 {
      C-5    2  i1
      C-5    2  tie
      C-5    4
      C-5    4  tie
      C-5    2
      C-5    2  tie
      C-5    8
      D-5    8
      E-5    4
      E-5    4  tie
      E-5    2
      E-5    2  tie
      E-5    2
      E-5    2  tie
      D-5    8
      C-5    8
      A-4    4
      A-4    4  tie
      A-4    2
      A-4    2  tie
      A-4    2
      A-4    2  tie
      A-4    8
      B-4    8
      A-4   24
      B-4    8
      B-4    2
      B-4    2  tie
      B-4    4
      B-4    4  tie
      B-4    2
      B-4    2  tie
      B-4    8
      C-5    8
      D-5    4
      D-5    4  tie
      D-5    2
      D-5    2  tie
      D-5    2
      D-5    2  tie
      B-4    8
      A-4    8
      G-4    4
      G-4    4  tie
      G-4    2
      G-4    2  tie
      G-4    2
      G-4    2  tie
      G-4    8
      F#4    8
      G-4   16
      C-4    4
      D-4    4
      E-4    4
      G-4    4
      C-5    2
      C-5    2  tie
      C-5    4
      C-5    4  tie
      C-5    2
      C-5    2  tie
      C-5    8
      D-5    8
      E-5    4
      E-5    4  tie
      E-5    2
      E-5    2  tie
      E-5    2
      E-5    2  tie
      D-5    8
      C-5    8
      A-5    4
      A-5    4  tie
      A-5    2
      A-5    2  tie
      A-5    2
      A-5    2  tie
      G-5    8
      F-5    8
      C-5   16
      A-4    4
      C-5    4
      F-5    4
      A-5    4
      G-5    4
      G-5    4  tie
      G-5    2
      G-5    2  tie
      G-5    2
      G-5    2  tie
      F-5    8
      E-5    8
      D-5    4
      D-5    4  tie
      D-5    2
      D-5    2  tie
      D-5    2
      D-5    2  tie
      C-5    8
      B-4    8
      E-5    4
      E-5    4  tie
      E-5    2
      E-5    2  tie
      E-5    2
      E-5    2  tie
      E-5    8
      D-5    8
      C-5   32
    }
    pattern 8 length=512 {
      C-0    8  tie
      A-5    2  i5
      A-5    2  tie
      A-5    4
      D-6    4
      A-5    4
      D-6    4
      F#6    4
      D-6    4
      D-6    4  tie
      D-6    2
      D-6    2  tie
      D-6    2
      D-6    2  tie
      F#6    4
      D-6    4
      F#6    4
      A-6    4
      F#6    4
      F#6    4  tie
      F#6    2
      F#6    2  tie
      F#6    2
      F#6    2  tie
      A-6    4
      F#6    4
      A-6    4
      D-7    4
      A-6   32
      A-6    8  tie
      B-5    2  i5
      B-5    2  tie
      B-5    4
      E-6    4
      B-5    4
      E-6    4
      G#6    4
      E-6    4
      E-6    4  tie
      E-6    2
      E-6    2  tie
      E-6    2
      E-6    2  tie
      G#6    4
      E-6    4
      G#6    4
      B-6    4
      G#6    4
      G#6    4  tie
      G#6    2
      G#6    2  tie
      G#6    2
      G#6    2  tie
      B-6    4
      G#6    4
      B-6    4
      E-7    4
      B-6   32
      B-6    8  tie
      C-6    2  i5
      C-6    2  tie
      C-6    4
      F-6    4
      C-6    4
      F-6    4
      A-6    4
      F-6    4
      F-6    4  tie
      F-6    2
      F-6    2  tie
      F-6    2
      F-6    2  tie
      A-6    4
      F-6    4
      A-6    4
      C-7    4
      A-6    4
      A-6    4  tie
      A-6    2
      A-6    2  tie
      A-6    2
      A-6    2  tie
      C-7    4
      A-6    4
      C-7    4
      F-7    4
      C-7   32
      C-7    8  tie
      D-6    2  i5
      D-6    2  tie
      D-6    4
      G-6    4
      D-6    4
      G-6    4
      B-6    4
      G-6    4
      G-6    4  tie
      G-6    2
      G-6    2  tie
      G-6    2
      G-6    2  tie
      B-6    4
      G-6    4
      B-6    4
      D-7    4
      B-6    4
      B-6    4  tie
      B-6    2
      B-6    2  tie
      B-6    2
      B-6    2  tie
      D-7    4
      B-6    4
      D-7    4
      G-7    4
      D-7   32
    }
    pattern 10 length=512 {
      A-4   24  i1
      A-4    4
      G#4    4
      A-4    8
      C-5    2
      C-5    2  tie
      C-5    4
      F-5    8
      A-5    8
      G-4   24
      G-4    4
      F#4    4
      G-4    8
      C-5    2
      C-5    2  tie
      C-5    4
      E-5    8
      G-5    8
      B-4   24
      A#4    8
      B-4    8
      D-5    8
      B-4    8
      A-4    8
      G-4   24
      F#4    8
      G-4    8
      E-5    8
      C-5    8
      G-4    8
      A-4   24
      A-4    4
      G#4    4
      A-4    8
      C-5    2
      C-5    2  tie
      C-5    4
      F-5    8
      A-5    8
      G-4   24
      G-4    4
      F#4    4
      G-4    8
      C-5    2
      C-5    2  tie
      C-5    4
      E-5    8
      G-5    8
      B-4    4
      B-4    4  tie
      B-4    4
      A#4    4
      B-4    8
      C-5    8
      D-5    4
      D-5    4  tie
      D-5    4
      C#5    4
      D-5    8
      B-4    8
      C-5    8
      D-4    8  i13
      D-4    8
      D-4    8
      B-3    4
      B-3    8
      B-3    4
      G#3    8
      G#3    8
    }
    pattern 12 length=512 {
      G-5    8  i6
      G-5    4
      G-5    4
      F#5    8
      F#5    4
      F#5    4
      E-5    8
      E-5    4
      E-5    4
      D-5    8
      D-5    4
      D-5    4
      A-5    8
      A-5    4
      A-5    4
      G-5    8
      G-5    4
      G-5    4
      F#5    8
      G-5    4
      F#5    4
      E-5    8
      E-5    4
      E-5    4
      G-5    8  i7
      G-5    4
      G-5    4
      F#5    8
      F#5    4
      F#5    4
      E-5    8
      E-5    4
      E-5    4
      D-5    8
      D-5    4
      D-5    4
      D-5    8
      D-5    4
      D-5    4
      D-5    8
      E-5    8
      D-5    8
      G-5    8
      B-5    8
      G-5    8
      C-6    8  i6
      C-6    4
      C-6    4
      B-5    8
      B-5    4
      B-5    4
      A-5    8
      A-5    4
      A-5    4
      G-5    8
      G-5    4
      G-5    4
      D-6    8
      D-6    4
      D-6    4
      C-6    8
      C-6    4
      C-6    4
      B-5    8
      C-6    4
      B-5    4
      A-5    8
      A-5    4
      A-5    4
      C-6    8  i7
      C-6    4
      C-6    4
      B-5    8
      B-5    4
      B-5    4
      A-5    8
      A-5    4
      A-5    4
      G-5    8
      G-5    4
      G-5    4
      E-5    8
      E-5    4
      E-5    4
      E-5    8
      D-5    8
      C-5    8
      E-5   24  i5
    }
    pattern 15 length=768 {
      B-4   24  i10
      D-5    8
      F-5   16
      E-5   16
      D-5    8  no_release
      D-5    8  no_release porta=33
      C-5   32
      B-4    8  no_release
      B-4    8  no_release porta=33
      A-4   32
      E-5   16  no_release
      E-5   16  porta=33
      D-5   32  no_release
      D-5   32
      B-4   24
      D-5    8
      F-5   16
      E-5   16
      D-5    8  no_release
      D-5    8  no_release porta=33
      C-5   32
      C-5    8  no_release
      C-5    8  no_release porta=32
      C#5   32
      E-5   16  no_release
      E-5   16  porta=33
      D-5   32  no_release
      D-5   32
      C-5   32
      D#5   16
      F#5   16
      E-5   32
      G-5   16  no_release
      G-5   16  no_release porta=41
      F#5   32
      A-5   16  no_release
      A-5   16  no_release porta=49
      G-5   16  no_release
      G-5   32  porta=49
      G-5    8  tie
      B-4    4  i17
      B-4    4
    }
    pattern 22 length=256 {
      C-0    4  i16
      C-3   28  no_release porta=4
      C-3   32  tie no_release
      C-3   32  tie no_release
      C-3   32  tie no_release
      C-3   32  tie no_release
      C-3   32  tie no_release
      C-3   32  tie no_release
      C-3   32  tie
    }
    pattern 24 length=256 {
      C-0    8  tie
      D-6    2  i5
      D-6    2  tie
      D-6    4
      G-6    4
      D-6    4
      G-6    4
      B-6    4
      G-6    4
      G-6    4  tie
      G-6    2
      G-6    2  tie
      G-6    2
      G-6    2  tie
      B-6    4
      G-6    4
      B-6    4
      D-7    4
      B-6    4
      B-6    4  tie
      B-6    2
      B-6    2  tie
      B-6    2
      B-6    2  tie
      D-7    4
      B-6    4
      D-7    4
      G-7    4  i19
      D-7   32  no_release
      D-7   32  tie no_release
      D-7   32  tie no_release
      D-7   32  tie no_release
      D-7   32  tie
    }
    pattern 26 length=32 {
      B-4    8  i17
      B-2    4  i18
      B-2    4
      B-2    8
      B-4    4  i17
      B-4    4
    }
    pattern 27 length=64 {
      B-4    8
      C-5    8
      B-4    8
      A-4    8
      B-4   16
      B-3    8  i13
      B-4    4  i17
      B-4    4
    }
    pattern 28 length=64 {
      B-4    8
      C-5    8
      B-4    8
      A-4    8
      B-4   16
      B-3    8  i13
      D-5    4  i17
      D-5    4
    }
    pattern 32 length=32 {
      D-5    8  i17
      D-3    4  i18
      D-3    4
      D-3    8
      D-5    4  i17
      D-5    4
    }
    pattern 33 length=64 {
      D-5    8
      E-5    8
      D-5    8
      C#5    8
      D-5   16
      B-3    8  i13
      D-5    4  i17
      D-5    4
    }
    pattern 34 length=64 {
      D-5    8
      E-5    8
      D-5    8
      C#5    8
      D-5    8
      E-5    8
      D-5    8
      C-5    8
    }
    pattern 35 length=64 {
      B-4    8
      C-5    8
      B-4    8
      C-5    8
      B-4    8
      C-5    8
      B-4    8
      C-5    8
    }
    pattern 40 length=256 {
      C-5    2
      C-5    2  tie
      C-5    4
      C-5    4  tie
      C-5    2
      C-5    2  tie
      C-5    8
      D-5    8
      E-5    4
      E-5    4  tie
      E-5    2
      E-5    2  tie
      E-5    2
      E-5    2  tie
      D-5    8
      C-5    8
      A-5    4
      A-5    4  tie
      A-5    2
      A-5    2  tie
      A-5    2
      A-5    2  tie
      G-5    8
      F-5    8
      C-5   16
      A-4    4
      C-5    4
      F-5    4
      A-5    4
      G-5    4
      G-5    4  tie
      G-5    2
      G-5    2  tie
      G-5    2
      G-5    2  tie
      F-5    8
      E-5    8
      D-5    4
      D-5    4  tie
      D-5    2
      D-5    2  tie
      D-5    2
      D-5    2  tie
      C-5    8
      B-4    8
      E-5    4
      E-5    4  tie
      E-5    2
      E-5    2  tie
      E-5    2
      E-5    2  tie
      E-5    8
      D-5    8
      C-5   32
    }
  }
  voice 2 {
    orderlist: 21 0 23 23 25 5 11 13 5 9 20 29 29 30 29 29 31 36 36 37 36 36 38 39 25 11 13 5 41 41 23 0 0 loop@0
    pattern 0 length=64 {
      C-0   32  tie
      C-0   32  tie
    }
    pattern 5 length=512 {
      E-4    2  i2
      E-4    2  tie
      E-4    4
      E-4    4  tie
      E-4    2
      E-4    2  tie
      E-4    8
      G-4    8
      C-5    4
      C-5    4  tie
      C-5    2
      C-5    2  tie
      C-5    2
      C-5    2  tie
      G-4    8
      E-4    8
      F-4    4
      F-4    4  tie
      F-4    2
      F-4    2  tie
      F-4    2
      F-4    2  tie
      F-4    8
      G-4    8
      F-4   24
      G-4    8
      D-4    2
      D-4    2  tie
      D-4    4
      D-4    4  tie
      D-4    2
      D-4    2  tie
      D-4    8
      G-4    8
      B-4    4
      B-4    4  tie
      B-4    2
      B-4    2  tie
      B-4    2
      B-4    2  tie
      G-4    8
      F-4    8
      E-4    4
      E-4    4  tie
      E-4    2
      E-4    2  tie
      E-4    2
      E-4    2  tie
      E-4    8
      D#4    8
      E-4   16
      E-3    4
      G-3    4
      C-4    4
      D-4    4
      E-4    2
      E-4    2  tie
      E-4    4
      E-4    4  tie
      E-4    2
      E-4    2  tie
      E-4    8
      G-4    8
      C-5    4
      C-5    4  tie
      C-5    2
      C-5    2  tie
      C-5    2
      C-5    2  tie
      G-4    8
      E-4    8
      F-5    4
      F-5    4  tie
      F-5    2
      F-5    2  tie
      F-5    2
      F-5    2  tie
      C-5    8
      A-4    8
      F-4   16
      F-4    4
      G-4    4
      A-4    4
      C-5    4
      E-5    4
      E-5    4  tie
      E-5    2
      E-5    2  tie
      E-5    2
      E-5    2  tie
      C-5    8
      G-4    8
      B-4    4
      B-4    4  tie
      B-4    2
      B-4    2  tie
      B-4    2
      B-4    2  tie
      G-4    8
      D-4    8
      C-5    4
      C-5    4  tie
      C-5    2
      C-5    2  tie
      C-5    2
      C-5    2  tie
      C-5    8
      G-4    8
      E-4   32
    }
    pattern 9 length=512 {
      C-0    8  tie
      D-5    2  i5
      D-5    2  tie
      D-5    4
      F#5    4
      D-5    4
      F#5    4
      A-5    4
      F#5    4
      F#5    4  tie
      F#5    2
      F#5    2  tie
      F#5    2
      F#5    2  tie
      A-5    4
      F#5    4
      A-5    4
      D-6    4
      A-5    4
      A-5    4  tie
      A-5    2
      A-5    2  tie
      A-5    2
      A-5    2  tie
      D-6    4
      A-5    4
      D-6    4
      A-6    4
      F#6   32
      F#6    8  tie
      E-5    2  i5
      E-5    2  tie
      E-5    4
      G#5    4
      E-5    4
      G#5    4
      B-5    4
      G#5    4
      G#5    4  tie
      G#5    2
      G#5    2  tie
      G#5    2
      G#5    2  tie
      B-5    4
      G#5    4
      B-5    4
      E-6    4
      B-5    4
      B-5    4  tie
      B-5    2
      B-5    2  tie
      B-5    2
      B-5    2  tie
      E-6    4
      B-5    4
      E-6    4
      B-6    4
      G#6   32
      G#6    8  tie
      F-5    2  i5
      F-5    2  tie
      F-5    4
      A-5    4
      F-5    4
      A-5    4
      C-6    4
      A-5    4
      A-5    4  tie
      A-5    2
      A-5    2  tie
      A-5    2
      A-5    2  tie
      C-6    4
      A-5    4
      C-6    4
      F-6    4
      C-6    4
      C-6    4  tie
      C-6    2
      C-6    2  tie
      C-6    2
      C-6    2  tie
      F-6    4
      C-6    4
      F-6    4
      C-7    4
      A-6   32
      A-6    8  tie
      G-5    2  i5
      G-5    2  tie
      G-5    4
      B-5    4
      G-5    4
      B-5    4
      D-6    4
      B-5    4
      B-5    4  tie
      B-5    2
      B-5    2  tie
      B-5    2
      B-5    2  tie
      D-6    4
      B-5    4
      D-6    4
      G-6    4
      D-6    4
      D-6    4  tie
      D-6    2
      D-6    2  tie
      D-6    2
      D-6    2  tie
      G-6    4
      D-6    4
      G-6    4
      D-7    4
      B-6   32
    }
    pattern 11 length=512 {
      F-4   24  i2
      F-4    4
      E-4    4
      F-4    8
      G-4    2
      G-4    2  tie
      G-4    4
      A-4    8
      C-5    8
      E-4   24
      E-4    4
      D#4    4
      E-4    8
      E-4    2
      E-4    2  tie
      E-4    4
      G-4    8
      E-5    8
      G-4   24
      F#4    8
      G-4    8
      B-4    8
      G-4    8
      F-4    8
      E-4   24
      D#4    8
      E-4    8
      C-5    8
      G-4    8
      E-4    8
      F-4   24
      F-4    4
      E-4    4
      F-4    8
      G-4    2
      G-4    2  tie
      G-4    4
      A-4    8
      C-5    8
      E-4   24
      E-4    4
      D#4    4
      E-4    8
      E-4    2
      E-4    2  tie
      E-4    4
      G-4    8
      E-5    8
      G-4    4
      G-4    4  tie
      G-4    4
      F#4    4
      G-4    8
      A-4    8
      B-4    4
      B-4    4  tie
      B-4    4
      A#4    4
      B-4    8
      F-4    8
      E-4    8
      C-0    4  i14
      A#0   32  no_release porta=48
      A#0   16  tie no_release
      A#0    4  tie
    }
    pattern 13 length=512 {
      C-5    8  i8
      C-5    4
      C-5    4
      C-5    8
      C-5    4
      C-5    4
      C-5    8
      C-5    4
      C-5    4
      C-5    8
      C-5    4
      C-5    4
      B-4    8
      B-4    4
      B-4    4
      B-4    8
      B-4    4
      B-4    4
      B-4    8
      B-4    4
      B-4    4
      B-4    8
      B-4    4
      B-4    4
      C-5    8
      C-5    4
      C-5    4
      C-5    8
      C-5    4
      C-5    4
      C-5    8
      C-5    4
      C-5    4
      C-5    8
      C-5    4
      C-5    4
      B-4    8
      B-4    4
      B-4    4
      B-4    8
      C-5    8
      A-4    8
      B-4    8
      D-5    8
      B-4    8
      F-5    8
      F-5    4
      F-5    4
      F-5    8
      F-5    4
      F-5    4
      F-5    8
      F-5    4
      F-5    4
      F-5    8
      F-5    4
      F-5    4
      E-5    8
      E-5    4
      E-5    4
      E-5    8
      E-5    4
      E-5    4
      E-5    8
      E-5    4
      E-5    4
      E-5    8
      E-5    4
      E-5    4
      F-5    8
      F-5    4
      F-5    4
      F-5    8
      F-5    4
      F-5    4
      F-5    8
      F-5    4
      F-5    4
      F-5    8
      F-5    4
      F-5    4
      C-5    8
      C-5    4
      C-5    4
      C-5    8
      G-4    8
      E-4    8
      C-5   24  i5
    }
    pattern 20 length=768 {
      G#4   24  i11
      B-4    8
      D-5   16
      C-5   16
      B-4    8  no_release
      B-4    8  no_release porta=25
      A-4   32
      G-4    8  no_release
      G-4    8  no_release porta=25
      F#4   32
      C-5   16  no_release
      C-5   16  porta=33
      B-4   32  no_release
      B-4   32
      G#4   24
      B-4    8
      D-5   16
      C-5   16
      B-4    8  no_release
      B-4    8  no_release porta=25
      A-4   32
      A-4    8  no_release
      A-4    8  no_release porta=32
      A#4   32
      C#5   16  no_release
      C#5   16  porta=33
      B-4   32  no_release
      B-4   32
      G#4   32
      C-5   16
      D#5   16
      C-5   32
      E-5   16  no_release
      E-5   16  no_release porta=41
      D-5   32
      C-5   16  no_release
      C-5   16  no_release porta=33
      B-4   16  no_release
      B-4   32  porta=41
      B-4    8  tie
      D#4    4  i17
      D#4    4
    }
    pattern 21 length=256 {
      C-0    4  i15
      C-3   28  no_release porta=4
      C-3   32  tie no_release
      C-3   32  tie no_release
      C-3   32  tie no_release
      C-3   32  tie no_release
      C-3   32  tie no_release
      C-3   32  tie no_release
      C-3   32  tie
    }
    pattern 23 length=128 {
      C-0    4  i14
      A#0   28  no_release porta=8
      A#0   32  tie no_release
      A#0   32  tie no_release
      A#0   32  tie
    }
    pattern 25 length=64 {
      C-5    8
      D-4    8  i13
      D-4    8
      D-4    8
      B-3    4
      B-3    8
      B-3    4
      G#3    8
      G#3    8
    }
    pattern 29 length=32 {
      D#4    8  i17
      B-1    4  i18
      B-1    4
      B-1    8
      D#4    4  i17
      D#4    4
    }
    pattern 30 length=64 {
      D#4    8
      A-4    8
      G-4    8
      F#4    8
      D#4   16
      D-4    8  i4
      D#4    4  i17
      D#4    4
    }
    pattern 31 length=64 {
      D#4    8
      A-4    8
      G-4    8
      F#4    8
      D#4   16
      D-4    8  i4
      F#4    4  i17
      F#4    4
    }
    pattern 36 length=32 {
      F#4    8  i17
      D-2    4  i18
      D-2    4
      D-2    8
      F#4    4  i17
      F#4    4
    }
    pattern 37 length=64 {
      F#4    8
      G-4    8
      F#4    8
      G-4    8
      F#4   16
      E-4    8  i4
      F#4    4  i17
      F#4    4
    }
    pattern 38 length=64 {
      F#4    8
      G-4    8
      F#4    8
      G-4    8
      F#4    8
      G-4    8
      F#4    8
      F#4    8
    }
    pattern 39 length=64 {
      F-4    8
      E-4    8
      F-4    8
      E-4    8
      F-4    8
      E-4    8
      F-4    8
      E-4    8
    }
    pattern 41 length=256 {
      E-4    2
      E-4    2  tie
      E-4    4
      E-4    4  tie
      E-4    2
      E-4    2  tie
      E-4    8
      G-4    8
      C-5    4
      C-5    4  tie
      C-5    2
      C-5    2  tie
      C-5    2
      C-5    2  tie
      G-4    8
      E-4    8
      F-5    4
      F-5    4  tie
      F-5    2
      F-5    2  tie
      F-5    2
      F-5    2  tie
      C-5    8
      A-4    8
      F-4   16
      F-4    4
      G-4    4
      A-4    4
      C-5    4
      E-5    4
      E-5    4  tie
      E-5    2
      E-5    2  tie
      E-5    2
      E-5    2  tie
      C-5    8
      G-4    8
      B-4    4
      B-4    4  tie
      B-4    2
      B-4    2  tie
      B-4    2
      B-4    2  tie
      G-4    8
      D-4    8
      C-5    4
      C-5    4  tie
      C-5    2
      C-5    2  tie
      C-5    2
      C-5    2  tie
      C-5    8
      G-4    8
      E-4   32
    }
  }
  voice 3 {
    orderlist: 14 14 14 14 14 1 2 3 1 1 2 3 1 2 1 3 1 2 1 3 1 6 3 6 3 3 1 3 1 1 2 3 1 1 2 3 1 6 6 7 7 2 2 3 3 7 16 6 3 7 16 17 18 19 3 6 3 18 18 18 18 6 6 6 6 3 3 2 1 3 1 2 1 3 1 6 3 6 3 3 1 3 1 1 2 3 1 1 2 3 1 1 2 3 1 1 2 3 1 14 14 loop@0
    pattern 1 length=64 {
      C-2    8  i3
      C-3    4
      C-3    4
      A#3    8  i4
      C-3    4  i3
      C-3    4
      C-2    8  i3
      C-3    4
      C-3    4
      A#3    8  i4
      C-3    4  i3
      C-3    4
    }
    pattern 2 length=64 {
      F-1    8  i3
      F-2    4
      F-2    4
      A#3    8  i4
      F-2    4  i3
      F-2    4
      F-1    8  i3
      F-2    4
      F-2    4
      A#3    8  i4
      F-2    4  i3
      F-2    4
    }
    pattern 3 length=64 {
      G-1    8  i3
      G-2    4
      G-2    4
      A#3    8  i4
      G-2    4  i3
      G-2    4
      G-1    8  i3
      G-2    4
      G-2    4
      A#3    8  i4
      G-2    4  i3
      G-2    4
    }
    pattern 6 length=64 {
      D-2    8  i3
      D-3    4
      D-3    4
      A#3    8  i4
      D-3    4  i3
      D-3    4
      D-2    8  i3
      D-3    4
      D-3    4
      A#3    8  i4
      D-3    4  i3
      D-3    4
    }
    pattern 7 length=64 {
      E-2    8  i3
      E-3    4
      E-3    4
      A#3    8  i4
      E-3    4  i3
      E-3    4
      E-2    8  i3
      E-3    4
      E-3    4
      A#3    8  i4
      E-3    4  i3
      E-3    4
    }
    pattern 14 length=128 {
      C-2   32  i9  no_release
      C-2   32  tie no_release
      C-2   32  tie no_release
      C-2   32  tie no_release
    }
    pattern 16 length=64 {
      A-1    8  i3
      A-2    4
      A-2    4
      A#3    8  i4
      A-2    4  i3
      A-2    4
      A-1    8  i3
      A-2    4
      A-2    4
      A#3    8  i4
      G-2    4  i3
      G-2    4
    }
    pattern 17 length=64 {
      F#1    8  i3
      F#2    4
      F#2    4
      A#3    8  i4
      F#2    4  i3
      F#2    4
      F#1    8  i3
      F#2    4
      F#2    4
      A#3    8  i4
      F#2    4  i3
      F#2    4
    }
    pattern 18 length=64 {
      B-1    8  i3
      B-2    4
      B-2    4
      A#3    8  i4
      B-2    4  i3
      B-2    4
      B-1    8  i3
      B-2    4
      B-2    4
      A#3    8  i4
      A-2    4  i3
      A-2    4
    }
    pattern 19 length=64 {
      G#1    8  i3
      G#2    4
      G#2    4
      A#3    8  i4
      G#2    4  i3
      G#2    4
      G#1    8  i3
      G#2    4
      G#2    4
      A#3    8  i4
      G#2    4  i3
      G#2    4
    }
  }
}
