version: 2
engine: chimera

psid {
  title:      "Chimera"
  author:     "Rob Hubbard"
  released:   "1985 Firebird"
  clock:      PAL
  sid:        6581
  start_song: 1
}

params {
  arp_interval: 12
  arp_period: 8
  first_frame_gate_off: false
  freeze_on_stop: false
  has_stop_fill: false
  incby2_every_frame: false
  incby2_onset: $11
  incby2_step: 1
  linear_pw_or: $40
  speed_ctr_init: 2
  stop_fill: $00
  suppress_first_notestart: false
  vib_onset: 8
}

init {
  voice 1 { ctrl: $41  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i5  slide_v: $34 }
  voice 2 { ctrl: $41  dur_field: $57  pwm_period: $00  pwm_dir: up  instr: i15  slide_v: $00 }
  voice 3 { ctrl: $41  dur_field: $57  pwm_period: $00  pwm_dir: up  instr: i3  slide_v: $03 }
}

instrument 1 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=4 init=$0742 min_hi=8 max_hi=14
  adsr:     $69 $86
  arp:      offsets=[0] period=8
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 2 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $0C $00
  arp:      offsets=[0, 12, 12, 12, 12, 12, 12, 12] period=8
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 3 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=2 init=$01C8 min_hi=8 max_hi=14
  adsr:     $0D $A0
  arp:      offsets=[0] period=8
  vibrato:  scale=3
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 4 {
  waveform: $81
  loop:     0
  pwm:      mode=none speed=0 init=$0200 min_hi=0 max_hi=0
  adsr:     $0F $0A
  arp:      offsets=[0, 12, 12, 12, 12, 12, 12, 12] period=8
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 5 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=1 init=$03E5 min_hi=8 max_hi=14
  adsr:     $00 $60
  arp:      offsets=[0, 12, 12, 12, 12, 12, 12, 12] period=8
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 6 {
  waveform: $41
  loop:     0
  pwm:      mode=bidirectional speed=65 init=$0800 min_hi=8 max_hi=14
  adsr:     $79 $89
  arp:      offsets=[0] period=8
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 7 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $08 $0A
  arp:      offsets=[0] period=8
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 8 {
  waveform: $11
  loop:     0
  pwm:      mode=none speed=0 init=$0500 min_hi=0 max_hi=0
  adsr:     $BF $00
  arp:      offsets=[0, 12, 12, 12, 12, 12, 12, 12] period=8
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 9 {
  waveform: $10
  loop:     0
  pwm:      mode=none speed=0 init=$0500 min_hi=0 max_hi=0
  adsr:     $BF $05
  arp:      offsets=[0, 12, 12, 12, 12, 12, 12, 12] period=8
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 10 {
  waveform: $81
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $0F $0F
  arp:      offsets=[0] period=8
  vibrato:  scale=1
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       inc_by2
}

instrument 11 {
  waveform: $11
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $0F $0F
  arp:      offsets=[0] period=8
  vibrato:  scale=1
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       inc_by2
}

instrument 12 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $0F $0F
  arp:      offsets=[0, 12, 12, 12, 12, 12, 12, 12] period=8
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 13 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=2 init=$0100 min_hi=8 max_hi=14
  adsr:     $0F $8F
  arp:      offsets=[0] period=8
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 14 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $05 $09
  arp:      offsets=[0, 12, 12, 12, 12, 12, 12, 12] period=8
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 15 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $05 $04
  arp:      offsets=[0, 12, 12, 12, 12, 12, 12, 12] period=8
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 16 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=1 init=$0280 min_hi=8 max_hi=14
  adsr:     $09 $80
  arp:      offsets=[0] period=8
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 17 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $09 $70
  arp:      offsets=[0] period=8
  vibrato:  scale=1
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 18 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0300 min_hi=0 max_hi=0
  adsr:     $2C $30
  arp:      offsets=[0] period=8
  vibrato:  scale=1
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       inc_by2
}

instrument 19 {
  waveform: $15
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $0F $0F
  arp:      offsets=[0, 12, 12, 12, 12, 12, 12, 12] period=8
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

subtune 0 music {
  tempo: 3
  voice 1 {
    orderlist: 6 7 7 7 7 4 5 4 5 8 9 12 4 4 13 13 8 9 29 4 4 13 13 15 15 17 17 19 20 19 21 29 4 13 15 17 19 20 19 21 19 20 19 21 29 12 34 loop@0
    pattern 4 length=96 {
      A-4    6  i1
      A-4    6
      A-4    3
      B-4    3
      G-4   24
      D-4    6
      A-4    6
      A-4    6
      A-4    3
      B-4    3
      D-5   24
      A-4    6
    }
    pattern 5 length=96 {
      G-4   12
      E-6   12  i2
      D-6   12
      A-5   12
      G-5   12
      D-5   12
      A-4   12
      G-4   12
    }
    pattern 6 length=96 {
      D-3    1  i5
      E-3    1
      G-3    1
      A-3    1
      D-4    1
      E-4    1
      E-3    1
      G-3    1
      A-3    1
      D-4    1
      E-4    1
      G-4    1
      G-3    1
      A-3    1
      D-4    1
      E-4    1
      G-4    1
      A-4    1
      A-3    1
      D-4    1
      E-4    1
      G-4    1
      A-4    1
      D-5    1
      D-4    1
      E-4    1
      G-4    1
      A-4    1
      D-5    1
      E-5    1
      E-4    1
      G-4    1
      A-4    1
      D-5    1
      E-5    1
      G-5    1
      G-4    1
      A-4    1
      D-5    1
      E-5    1
      G-5    1
      A-5    1
      A-4    1
      D-5    1
      E-5    1
      G-5    1
      A-5    1
      D-6    1
      D-5    1
      E-5    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      E-5    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
    }
    pattern 7 length=48 {
      D-5    1
      E-5    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      E-5    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
    }
    pattern 8 length=48 {
      B-4    3  i6
      C-5    3
      G-5    9
      F#5    9
      E-5    9
      D-5    9
      C-5    6
    }
    pattern 9 length=48 {
      B-4    3
      C-5    3
      G-5    9
      F#5    9
      B-5    9
      C-6    9
      D-6    6
    }
    pattern 12 length=96 {
      A-5    3  i1
      G-5    3
      G-5    6
      G-5   12
      D-6   12  i2
      A-5   12
      G-5   24
      D-4    6  i7
      D-4    3
      B-3    6
      B-3    3
      G#3    6
    }
    pattern 13 length=96 {
      C-5    6  i1
      C-5    6
      C-5    3
      D-5    3
      A#4   24
      F-4    6
      C-5    6
      C-5    6
      C-5    3
      D-5    3
      F-5   24
      C-4    6  i7
    }
    pattern 15 length=96 {
      E-5    6  i1
      E-5    6
      E-5    3
      F-5    3
      E-5   24
      A-4    6
      E-5    6
      E-5    6
      E-5    3
      F-5    3
      G-5   18
      B-3    6  i7
      G#3    6
    }
    pattern 17 length=96 {
      D-5    6  i1
      D-5    6
      D-5    3
      E-5    3
      C-5   24
      G-4    6
      D-5    6
      D-5    6
      D-5    3
      E-5    3
      G-5   18
      B-3    6  i7
      G#3    3
      G#3    3
    }
    pattern 19 length=48 {
      B-4    3  i6
      C-5    3
      G-5    3
      G-5    3
      G-5    3
      F#5    3
      F#5    3
      F#5    3
      E-5    3
      E-5    3
      E-5    3
      D-5    3
      D-5    3
      D-5    3
      C-5    3
      C-5    3
    }
    pattern 20 length=48 {
      B-4    3
      C-5    3
      G-5    3
      G-5    3
      G-5    3
      F#5    3
      F#5    3
      F#5    3
      B-5    3
      B-5    3
      B-5    3
      A-5    3
      A-5    3
      A-5    3
      F#5    3
      F#5    3
    }
    pattern 21 length=48 {
      B-4    3
      C-5    3
      G-5    3
      G-5    3
      G-5    3
      F#5    3
      F#5    3
      F#5    3
      B-5    3
      B-5    3
      B-5    3
      C-6    3
      C-6    3
      C-6    3
      D-6    3
      D-6    3
    }
    pattern 29 length=96 {
      A-5    3  i1
      G-5    3
      G-5    6
      G-5    6
      D-6    6  i2
      A-5    6
      G-5    6
      A-5    6
      G-5    6
      D-5    6
      A-4    6
      G-4    6
      G-5    6
      D-4    3  i7
      D-4    6
      B-3    6
      B-3    3
      G#3    3
      G#3    3
    }
    pattern 34 length=192 {
      G-6   24  i12  no_release
      G-6   24  no_release
      G-6   24  no_release
      G-6   24  no_release
      G-6   24  tie no_release
      G-6   24  tie no_release
      G-6   24  tie no_release
      G-6   24  tie no_release
    }
  }
  voice 2 {
    orderlist: 0 0 0 27 32 31 6 7 7 7 7 7 27 10 11 7 28 6 6 14 14 10 11 7 28 6 6 14 14 16 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 28 18 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 27 22 23 22 24 7 7 6 14 16 25 25 25 25 25 25 25 25 18 26 26 26 26 26 26 26 26 22 23 22 24 22 23 22 24 7 7 7 7 7 7 7 7 loop@0
    pattern 0 length=48 {
      C-0   24  tie
      C-0   24  tie
    }
    pattern 6 length=96 {
      D-3    1  i5
      E-3    1
      G-3    1
      A-3    1
      D-4    1
      E-4    1
      E-3    1
      G-3    1
      A-3    1
      D-4    1
      E-4    1
      G-4    1
      G-3    1
      A-3    1
      D-4    1
      E-4    1
      G-4    1
      A-4    1
      A-3    1
      D-4    1
      E-4    1
      G-4    1
      A-4    1
      D-5    1
      D-4    1
      E-4    1
      G-4    1
      A-4    1
      D-5    1
      E-5    1
      E-4    1
      G-4    1
      A-4    1
      D-5    1
      E-5    1
      G-5    1
      G-4    1
      A-4    1
      D-5    1
      E-5    1
      G-5    1
      A-5    1
      A-4    1
      D-5    1
      E-5    1
      G-5    1
      A-5    1
      D-6    1
      D-5    1
      E-5    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      E-5    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
    }
    pattern 7 length=48 {
      D-5    1
      E-5    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      E-5    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
      G-5    1
      A-5    1
      D-6    1
      E-6    1
      G-6    1
      A-6    1
    }
    pattern 10 length=48 {
      G-4    3  i6
      A-4    3
      E-5    9
      D-5    9
      C-5    9
      B-4    9
      A-4    6
    }
    pattern 11 length=48 {
      G-4    3
      A-4    3
      E-5    9
      D-5    9
      G-5    9
      A-5    9
      B-5    6
    }
    pattern 14 length=96 {
      F-3    1  i5
      G-3    1
      A#3    1
      C-4    1
      D-4    1
      F-4    1
      G-3    1
      A#3    1
      C-4    1
      D-4    1
      F-4    1
      G-4    1
      A#3    1
      C-4    1
      D-4    1
      F-4    1
      G-4    1
      A#4    1
      C-4    1
      D-4    1
      F-4    1
      G-4    1
      A#4    1
      C-5    1
      D-4    1
      F-4    1
      G-4    1
      A#4    1
      C-5    1
      D-5    1
      F-4    1
      G-4    1
      A#4    1
      C-5    1
      D-5    1
      F-5    1
      G-4    1
      A#4    1
      C-5    1
      D-5    1
      F-5    1
      G-5    1
      A#4    1
      C-5    1
      D-5    1
      F-5    1
      G-5    1
      A#5    1
      C-5    1
      D-5    1
      F-5    1
      G-5    1
      A#5    1
      C-6    1
      D-5    1
      F-5    1
      G-5    1
      A#5    1
      C-6    1
      D-6    1
      F-5    1
      G-5    1
      A#5    1
      C-6    1
      D-6    1
      F-6    1
      G-5    1
      A#5    1
      C-6    1
      D-6    1
      F-6    1
      G-6    1
      A#5    1
      C-6    1
      D-6    1
      F-6    1
      G-6    1
      A#6    1
      A#5    1
      C-6    1
      D-6    1
      F-6    1
      G-6    1
      A#6    1
      A#5    1
      C-6    1
      D-6    1
      F-6    1
      G-6    1
      A#6    1
      A#5    1
      C-6    1
      D-6    1
      F-6    1
      G-6    2
    }
    pattern 16 length=48 {
      G-3    1  i8
      A-3    1
      C#4    1
      E-4    1
      F-4    1
      G-4    1
      A-3    1
      C#4    1
      E-4    1
      F-4    1
      G-4    1
      A-4    1
      C#4    1
      E-4    1
      F-4    1
      G-4    1
      A-4    1
      C#5    1
      E-4    1
      F-4    1
      G-4    1
      A-4    1
      C#5    1
      E-5    1
      F-4    1
      G-4    1
      A-4    1
      C#5    1
      E-5    1
      F-5    1
      G-4    1
      A-4    1
      C#5    1
      E-5    1
      F-5    1
      G-5    1
      A-4    1
      C#5    1
      E-5    1
      F-5    1
      G-5    1
      A-5    1
      C#5    1  i8
      E-5    1
      F-5    1
      G-5    1
      A-5    1
      C#6    1  i9
    }
    pattern 18 length=48 {
      G-3    1  i8
      C-4    1
      D-4    1
      E-4    1
      G-4    1
      C-5    1
      C-4    1
      D-4    1
      E-4    1
      G-4    1
      C-5    1
      D-5    1
      D-4    1
      E-4    1
      G-4    1
      C-5    1
      D-5    1
      E-5    1
      E-4    1
      G-4    1
      C-5    1
      D-5    1
      E-5    1
      G-5    1
      G-4    1
      C-5    1
      D-5    1
      E-5    1
      G-5    1
      C-6    1
      C-5    1
      D-5    1
      E-5    1
      G-5    1
      C-6    1
      D-6    1
      D-5    1
      E-5    1
      G-5    1
      C-6    1
      D-6    1
      E-6    1
      E-5    1  i8
      G-5    1
      C-6    1
      D-6    1
      E-6    1
      G-6    1  i9
    }
    pattern 22 length=48 {
      G-4    3  i6
      A-4    3
      E-5    3
      E-5    3
      E-5    3
      D-5    3
      D-5    3
      D-5    3
      C-5    3
      C-5    3
      C-5    3
      B-4    3
      B-4    3
      B-4    3
      A-4    3
      A-4    3
    }
    pattern 23 length=48 {
      G-4    3
      A-4    3
      E-5    3
      E-5    3
      E-5    3
      D-5    3
      D-5    3
      D-5    3
      G-5    3
      G-5    3
      G-5    3
      F#5    3
      F#5    3
      F#5    3
      D-5    3
      D-5    3
    }
    pattern 24 length=48 {
      G-4    3
      A-4    3
      E-5    3
      E-5    3
      E-5    3
      D-5    3
      D-5    3
      D-5    3
      G-5    3
      G-5    3
      G-5    3
      A-5    3
      A-5    3
      A-5    3
      B-5    3
      B-5    3
    }
    pattern 25 length=6 {
      C#5    1  i8
      E-5    1
      F-5    1
      G-5    1
      A-5    1
      C#6    1  i9
    }
    pattern 26 length=6 {
      E-5    1  i8
      G-5    1
      C-6    1
      D-6    1
      E-6    1
      G-6    1  i9
    }
    pattern 27 length=48 {
      C-0    2  tie
      A#0   22  i10  no_release
      A#0   21  tie no_release
      A#0    3  tie
    }
    pattern 28 length=48 {
      C-0    2  tie
      G-5   22  i11  no_release
      G-5   21  tie no_release
      G-5    3  tie
    }
    pattern 31 length=24 {
      D-4    3  i7
      D-4    6
      B-3    6
      B-3    3
      G#3    3
      G#3    3
    }
    pattern 32 length=72 {
      G-6   24  i12  no_release
      G-6   24  no_release
      G-6   24
    }
  }
  voice 3 {
    orderlist: 0 0 0 30 1 1 1 1 1 1 1 1 1 1 3 3 1 1 1 1 1 1 2 2 2 2 3 3 1 1 1 1 1 1 2 2 2 2 1 1 1 1 1 1 1 1 3 3 3 3 1 1 1 1 2 2 1 1 1 1 3 3 3 3 3 3 3 3 1 1 1 1 33 loop@0
    pattern 0 length=48 {
      C-0   24  tie
      C-0   24  tie
    }
    pattern 1 length=48 {
      G-1    6  i3
      G-1    6
      B-3    6  i4
      G-1    3  i3
      G-1    3
      D-2    3  no_release porta=12
      E-2    3
      D-2    6
      B-3    6  i4
      A-2    1  i3
      A-2    2  no_release porta=19
      G-2    3
    }
    pattern 2 length=48 {
      A#1    6  i3
      A#1    6
      B-3    6  i4
      A#1    3  i3
      A#1    3
      F-2    3  no_release porta=14
      G-2    3
      F-2    6
      B-3    6  i4
      C-3    1  i3
      C-3    2  no_release porta=23
      A#2    3
    }
    pattern 3 length=48 {
      D-2    6  i3
      D-2    6
      B-3    6  i4
      D-2    3  i3
      D-2    3
      A-2    3  no_release porta=20
      B-2    3
      A-2    6
      B-3    6  i4
      E-3    1  i3
      E-3    2  no_release porta=31
      D-3    3
    }
    pattern 30 length=48 {
      D-4    3  i7
      D-4    6
      D-4    3
      D-4    6
      B-3    3
      B-3    6
      B-3    3
      B-3    6
      G#3    3
      G#3    3
      G#3    6
    }
    pattern 33 length=192 {
      G-1   24  i13  no_release
      G-1   24  no_release
      G-1   24  no_release
      G-1   24  no_release
      G-1   24  tie no_release
      G-1   24  tie no_release
      G-1   24  tie no_release
      G-1   24  tie no_release
    }
  }
}

subtune 1 music {
  tempo: 3
  voice 1 {
    orderlist: 48 48 48 48 39 40 39 41 42 42 39 41 45 45 46 46 39 41 42 42 39 41 39 41 48 48 48 48 loop@0
    pattern 39 length=92 {
      B-4    8  i16
      B-4    8
      B-4    4  no_release porta=32
      C#5    4
      A-4    4
      A-4   12
      B-5    8  i2
      A-5    8
      E-5    4
      E-4    4  i16
      A-4    8
      A-4    8
      A-4    4  no_release porta=32
      B-4    4
      A-4    4
    }
    pattern 40 length=36 {
      E-5   12
      E-5    8  i2
      B-4    8
      A-4    8
    }
    pattern 41 length=36 {
      A-4   12
      A-5    8  i2
      E-5    8
      A-4    8
    }
    pattern 42 length=128 {
      C#6    4  i17
      D-6    4
      B-6   12
      C#6    4
      A-6    8
      G#6    8
      B-5    4
      F#6    8
      B-5    4
      E-6    8
      C#6    4
      D-6    4
      A-6   12
      A-5    4
      G#6    8
      F#6    8
      A-5    4
      E-6    8
      A-5    4
      D-6    8
    }
    pattern 45 length=128 {
      G#3    4  i18
      A-3    4
      E-4    4
      F#4   24
      B-4    4  i16
      C#5    4
      B-4    4
      D-5    4  no_release porta=96
      E-5    4
      C#5    4
      B-4    2
      B-4    2  tie
      A-3    4  i18
      B-3    4
      E-4    4
      F#4   24
      B-4    4  i16
      C#5    4
      B-4    4
      D-5    4  no_release porta=96
      E-5    4
      C#5    4
      B-4    2
      B-4    2  tie
    }
    pattern 46 length=128 {
      C#4    4  i18
      D-4    4
      A-4    4
      B-4   12
      C#5    4  i2
      D-5    4
      A-5    4
      B-5    8
      E-5    4  i16
      G-5    4  no_release porta=112
      A-5    4
      F#5    4
      E-5    2
      E-5    2  tie
      B-3    4  i18
      D-4    4
      E-4    4
      A-4   12
      B-4    4  i2
      D-5    4
      E-5    4
      A-5    8
      E-5    4  i16
      G-5    4  no_release porta=112
      A-5    4
      F#5    4
      E-5    2
      E-5    2  tie
    }
    pattern 48 length=32 {
      C-0   32  tie
    }
  }
  voice 2 {
    orderlist: 38 38 38 38 38 38 47 47 47 47 38 38 38 38 47 47 38 38 47 47 38 38 47 47 47 47 38 38 38 38 48 48 48 48 loop@0
    pattern 38 length=64 {
      E-3    4  i14
      A-6    2  i15
      A-6    2
      A-5    2
      A-6    2
      A-3    4  i14
      A-5    2  i15
      A-5    2
      A-6    2
      A-5    2
      E-4    4  i14
      A-6    2  i15
      A-6    2
      A-5    2
      A-6    2
      E-3    4  i14
      A-5    2  i15
      A-5    2
      A-6    2
      A-5    2
      A-3    4  i14
      A-6    2  i15
      A-5    2
      E-4    4  i14
      A-6    2  i15
      A-5    2
    }
    pattern 47 length=64 {
      E-3    4  i19
      A-6    2  i15
      A-6    2
      A-5    2
      A-6    2
      A-3    4  i19
      A-5    2  i15
      A-5    2
      A-6    2
      A-5    2
      E-4    4  i19
      A-6    2  i15
      A-6    2
      A-5    2
      A-6    2
      E-3    4  i19
      A-5    2  i15
      A-5    2
      A-6    2
      A-5    2
      A-3    4  i19
      A-6    2  i15
      A-5    2
      E-4    4  i19
      A-6    2  i15
      A-5    2
    }
    pattern 48 length=32 {
      C-0   32  tie
    }
  }
  voice 3 {
    orderlist: 35 35 35 35 37 37 35 35 37 37 35 35 36 36 35 35 36 36 35 35 37 37 35 35 43 43 44 44 43 43 44 44 36 36 35 35 36 36 35 35 37 37 35 35 36 36 35 35 36 36 35 35 35 35 35 35 35 35 35 35 35 35 35 35 loop@0
    pattern 35 length=32 {
      A-1    4  i3
      A-1    4
      B-3    4  i4
      A-1    4  i3
      A-1    4
      A-1    4
      B-3    4  i4
      A-1    4  i3
    }
    pattern 36 length=32 {
      E-2    4  i3
      E-2    4
      B-3    4  i4
      E-2    4  i3
      E-2    4
      E-2    4
      B-3    4  i4
      E-2    4  i3
    }
    pattern 37 length=32 {
      D-2    4  i3
      D-2    4
      B-3    4  i4
      D-2    4  i3
      D-2    4
      D-2    4
      B-3    4  i4
      D-2    4  i3
    }
    pattern 43 length=32 {
      F#1    4  i3
      F#1    4
      B-3    4  i4
      F#1    4  i3
      F#1    4
      F#1    4
      B-3    4  i4
      F#1    4  i3
    }
    pattern 44 length=32 {
      B-1    4  i3
      B-1    4
      B-3    4  i4
      B-1    4  i3
      B-1    4
      B-1    4
      B-3    4  i4
      B-1    4  i3
    }
  }
}

subtune 2 digi {
  sample: Chimera.sample2.flac
}

subtune 3 digi {
  sample: Chimera.sample3.flac
}
