version: 2
engine: commando

psid {
  title:      "Commando"
  author:     "Rob Hubbard"
  released:   "1985 Elite"
  clock:      PAL
  sid:        6581
  start_song: 1
}

params {
  arp_interval: 12
  arp_period: 2
  first_frame_gate_off: false
  freeze_on_stop: false
  has_stop_fill: false
  incby2_every_frame: false
  incby2_onset: $03
  incby2_step: 2
  linear_pw_or: $00
  speed_ctr_init: 0
  stop_fill: $00
  suppress_first_notestart: false
  vib_onset: 6
}

init {
  voice 1 { ctrl: $00  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i1  slide_v: $02 }
  voice 2 { ctrl: $00  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i10  slide_v: $00 }
  voice 3 { ctrl: $00  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i3  slide_v: $C0 }
}

instrument 1 {
  waveform: $41
  loop:     0
  pwm:      mode=bidirectional speed=224 init=$0900 min_hi=8 max_hi=14
  adsr:     $29 $5F
  arp:      offsets=[0] period=2
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 2 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0180 min_hi=0 max_hi=0
  adsr:     $06 $4B
  arp:      offsets=[0, 12] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 3 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=22 init=$0180 min_hi=8 max_hi=14
  adsr:     $09 $9F
  arp:      offsets=[0] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 4 {
  waveform: $81
  loop:     0
  pwm:      mode=none speed=0 init=$0200 min_hi=0 max_hi=0
  adsr:     $0A $09
  arp:      offsets=[0, 12] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 5 {
  waveform: $43
  loop:     0
  pwm:      mode=none speed=0 init=$0200 min_hi=0 max_hi=0
  adsr:     $0F $C4
  arp:      offsets=[0] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide inc_by2
}

instrument 6 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=2 init=$0880 min_hi=8 max_hi=14
  adsr:     $05 $A9
  arp:      offsets=[0, 12] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 7 {
  waveform: $41
  loop:     0
  pwm:      mode=bidirectional speed=224 init=$0800 min_hi=8 max_hi=14
  adsr:     $38 $7A
  arp:      offsets=[0] period=2
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 8 {
  waveform: $15
  loop:     0
  pwm:      mode=none speed=0 init=$0180 min_hi=0 max_hi=0
  adsr:     $0D $FB
  arp:      offsets=[0, 12] period=2
  vibrato:  scale=1
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 9 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=3 init=$0800 min_hi=8 max_hi=14
  adsr:     $49 $5B
  arp:      offsets=[0] period=2
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 10 {
  waveform: $21
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $04 $6F
  arp:      offsets=[0, 12] period=2
  vibrato:  scale=3
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 11 {
  waveform: $41
  loop:     0
  pwm:      mode=linear speed=1 init=$0300 min_hi=8 max_hi=14
  adsr:     $09 $6B
  arp:      offsets=[0, 12] period=2
  vibrato:  scale=2
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 12 {
  waveform: $43
  loop:     0
  pwm:      mode=none speed=0 init=$0200 min_hi=0 max_hi=0
  adsr:     $07 $09
  arp:      offsets=[0] period=2
  vibrato:  scale=1
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

instrument 13 {
  waveform: $41
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $09 $0A
  arp:      offsets=[0] period=2
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
  fx:       freq_slide
}

subtune 0 music {
  tempo: 3
  voice 1 {
    orderlist: 19 19 19 19 7 7 9 12 12 16 16 16 16 15 15 17 17 18 23 23 23 23 23 23 23 23 16 16 16 16 23 23 23 23 16 16 23 23 26 27 28 28 28 28 29 29 29 29 30 30 30 30 15 23 23 31 16 16 23 17 23 18 23 31 loop@0
    pattern 7 length=256 {
      D-4    2  i4
      A-4    2  i1
      A-4    4
      A-4    4
      A-4    4
      A-4    8
      A-4    6
      A-4    4
      E-5    2
      E-5    4
      E-5    4
      E-5    4
      E-5    8
      G#3    8  i13
      F-5    8  i1
      E-5    8
      F-5    8
      E-5    8
      E-5    2  tie
      B-4    2
      B-4    4
      B-4    4
      B-4    4
      B-4    8
      G#3    8  i13
      D-4    2  i4
      C-5    2  i1
      C-5    4
      C-5    4
      C-5    4
      C-5    8
      C-5    6
      C-5    4
      G-5    2
      G-5    4
      G-5    4
      G-5    4
      G-5    8
      G#3    8  i13
      G#5    8  i1
      G-5    8
      G#5    8
      G-5    8
      G-5    2  tie
      D-5    2
      D-5    4
      D-5    4
      D-5    4
      D-5    8
      B-3    4  i13
      G#3    2
      G#3    2
    }
    pattern 9 length=128 {
      D-4    4  i4
      D-4    4
      A-4    4  i1
      A-4    4
      A-4    2
      A-4    2
      A-4    4
      B-4    4
      C-5    4
      D-5    2
      D-5    2
      D-5    4
      D-5    4
      D-5    4
      D-5    8
      G#3    4  i13
      D-5    2  i1
      E-5    2
      F-5    2
      F-5    2
      E-5    4
      D-5    4
      C-5    4
      B-4    4
      A-4    4
      G#4    8
      D-4    2  i4
      A-4    2  i1
      A-4    4
      A-4    4
      B-4    4
      A-4    8
      G#3    8  i13
    }
    pattern 12 length=128 {
      C-5    2  i6
      B-4    4
      A#4    2
      A-4    4
      C-5    2
      B-4    4
      A#4    2
      A-4    4
      C-5    2
      B-4    4
      A#4    2
      A-4    4
      C-5    2
      B-4    4
      A#4    2
      A-4    4
      C-5    2
      B-4    4
      A-4    2
      F-5    4
      E-5    4
      F-5    2
      E-5    4
      D#5    2
      D-5    4
      F-5    2
      E-5    4
      D#5    2
      D-5    4
      F-5    4
      E-5    4
      B-4    2
      A#4    4
      A-4    2
      G#4    4
      B-4    2
      A#4    4
      A-4    2
      G#4    4
      C-5    4
      B-4    4
    }
    pattern 15 length=128 {
      F#5   12  i7
      F#5    4  no_release porta=79
      E-5    8
      C#5    4
      B-4    4
      B-4    4  no_release porta=63
      A#4    4
      A#4    4
      G#3    4  i13
      G#3    4
      A#4    2  i7
      A#4    2
      B-4    4
      C#5    4
      C#5   12
      C#5    4
      E-5    6
      C#5    6
      B-4    4  no_release porta=40
      C#5    8
      C#5   16  porta=81
      G#3    4  i13
      G#3    4
    }
    pattern 16 length=32 {
      C-5    2  i7
      B-4    4
      A#4    2
      A-4    4
      C-5    2
      B-4    4
      A#4    2
      A-4    4
      C-5    4
      D-5    4
    }
    pattern 17 length=64 {
      D-5    8  i7
      G#3    4  i13
      D-5    2  i7
      D-5    2
      E-5    6
      D-5    6
      C-5    4  no_release porta=40
      D-5    8
      B-3    4  i13
      G#3   12
      B-3    4
      G#3    4
    }
    pattern 18 length=128 {
      E-5    8  i7
      G#3    4  i13
      E-5    2  i7
      E-5    2
      F#5    6
      E-5    6
      D-5    4  no_release porta=40
      E-5    8
      B-3    4  i13
      G#3   12
      B-3    4
      G#3    4
      E-5    8  i7
      G#3    4  i13
      E-5    2  i7
      E-5    2
      F#5    6
      E-5    6
      D-5    4  no_release porta=40
      E-5    6
      F#5    6
      G#5    4
      F#5    6
      G#5    6
      A-5    4
    }
    pattern 19 length=64 {
      E-7    4  i8
      A-6    4
      A-4    4  i2
      A-4    4
      A-4    6
      A-4    6
      G-4    6
      A-4    2
      A-4    4
      A-4    4
      G-4    4
      A-4    2
      G-4    2
      A-4    4
      E-7    4  i8
      A-6    4
    }
    pattern 23 length=32 {
      A#5    2  i6
      A#5    2
      A#5    2
      A#5    2
      A#5    2
      A#5    2
      G#5    2
      A#5    2
      A#5    2
      G#5    2
      A#5    4
      A#5    2
      A#5    2
      G#5    2
      G#5    2
    }
    pattern 26 length=384 {
      G-4    8  i7  no_release
      G-4    8  no_release porta=40
      A-4   24
      G-4    4
      A-4    4
      D-5    4
      C-5    4
      A-4    8
      C-5    8  no_release
      C-5    8  no_release porta=42
      D-5   24
      D-5    4
      G-5    4
      F#5    4
      D-5    4
      A-4    8
      G-4    8  no_release
      G-4    8  no_release porta=16
      A-4   24
      D#5    8  no_release porta=41
      D-5    4
      C-5    4
      A-4    8
      D-5    8  no_release
      D-5    8  no_release porta=41
      C-5   24
      D-5    4
      E-5    4
      G-5    4
      F#5    4
      G-5    4
      A-5    4
      G-5    8  no_release
      G-5    8  no_release porta=52
      A-5    8
      A-5    2
      A-5    4
      A-5    2
      A-5    2
      A-5    4
      G-5    2
      A-5    4
      G-5    2
      F#5    4
      G-5    2
      F#5    4
      E-5    4
      D-5    4
      D-5    2
      D-5    4
      C-5    2
      D-5    4
      C-5    2
      B-4    4
      C-5    2
      B-4    4
      A-4    4
      G-4    4
      A-4    2
      A-4    4
      G-4    2
      A-4    4
      B-4    2
      C-5    4
      D-5    2
      E-5    4
      F#5    4
      G-5    4
    }
    pattern 27 length=128 {
      B-5    8  no_release
      B-5    8  no_release porta=49
      A-5   24
      G-5    4
      A-5    4
      C-6    2
      C-6    2
      A-5    4
      D-6    2
      D-6    2
      C-6    4
      E-6    8  no_release
      E-6    8  no_release porta=81
      D-6   32
      D-6    2  tie
      E-6    2
      E-6    2
      E-5    2
      F-6    2
      E-5    2
      C-6    2
      D-6    2
    }
    pattern 28 length=32 {
      E-6    2
      E-6    2
      E-5    4
      D-6    4
      E-5    2
      C-6    4
      E-5    2
      B-5    4
      C-6    2
      E-5    2
      C-6    2
      D-6    2
    }
    pattern 29 length=32 {
      E-6    2
      E-6    2
      E-5    4
      D#6    4
      E-5    2
      C#6    4
      E-5    2
      B-5    4
      C#6    2
      E-5    2
      C#6    2
      D#6    2
    }
    pattern 30 length=32 {
      C#6    2
      C#6    2
      C#5    4
      B-5    4
      C#5    2
      A#5    4
      C#5    2
      G#5    4
      F#5    2
      C#5    2
      B-5    2
      C#6    2
    }
    pattern 31 length=32 {
      G#8    8  i8
      G#8   16  tie
      G#3    4  i13
      G#3    4
    }
  }
  voice 2 {
    orderlist: 8 8 8 10 8 10 8 8 8 19 19 20 20 20 20 21 21 22 22 24 24 24 24 24 24 24 24 19 19 24 24 24 24 19 24 24 19 19 19 19 19 19 19 19 19 19 20 20 20 20 20 20 24 24 31 19 24 21 24 22 22 24 31 loop@0
    pattern 8 length=128 {
      G#8    2  i5
      G#8    2
      G#8    2
      G#8    2
      E-4    4  i2
      E-4    4
      F-4    6
      E-4    6
      D-4    4
      G#8    2  i5
      G#8    2
      G#8    2
      G#8    2
      E-4    4  i2
      E-4    4
      E-4    8
      E-4    8  tie
      G#8    2  i5
      G#8    2
      G#8    2
      G#8    2
      E-4    4  i2
      E-4    4
      F-4    6
      E-4    6
      D-4    4
      D-4    2  tie
      E-4    2  i2
      E-4    4
      E-4    4
      E-4    4
      E-4    8
      E-4    8  tie
    }
    pattern 10 length=128 {
      G#8    2  i5
      G#8    2
      G#8    2
      G#8    2
      G-4    4  i2
      G-4    4
      G#4    6
      G-4    6
      F-4    4
      G#8    2  i5
      G#8    2
      G#8    2
      G#8    2
      G-4    4  i2
      G-4    4
      G-4    8
      G-4    8  tie
      G#8    2  i5
      G#8    2
      G#8    2
      G#8    2
      G-4    4  i2
      G-4    4
      G#4    6
      G-4    6
      F-4    4
      F-4    2  tie
      G-4    2  i2
      G-4    4
      G-4    4
      G-4    4
      G-4    8
      G-4    8  tie
    }
    pattern 19 length=64 {
      E-7    4  i8
      A-6    4
      A-4    4  i2
      A-4    4
      A-4    6
      A-4    6
      G-4    6
      A-4    2
      A-4    4
      A-4    4
      G-4    4
      A-4    2
      G-4    2
      A-4    4
      E-7    4  i8
      A-6    4
    }
    pattern 20 length=64 {
      C#7    4  i8
      F#6    4
      C#4    4  i2
      C#4    4
      C#4    6
      C#4    6
      B-3    6
      C#4    2
      C#4    4
      C#4    4
      B-3    4
      C#4    2
      B-3    2
      C#4    4
      C#7    4  i8
      F#6    4
    }
    pattern 21 length=64 {
      A-7    4  i8
      D-7    4
      D-4    4  i2
      D-4    4
      D-4    6
      D-4    6
      C-4    6
      D-4    2
      D-4    4
      D-4    4
      C-4    4
      D-4    2
      C-4    2
      D-4    4
      A-7    4  i8
      D-7    4
    }
    pattern 22 length=64 {
      B-7    4  i8
      E-7    4
      E-4    4  i2
      E-4    4
      E-4    6
      E-4    6
      D-4    6
      E-4    2
      E-4    4
      E-4    4
      D-4    4
      E-4    2
      D-4    2
      E-4    4
      B-7    4  i8
      E-7    4
    }
    pattern 24 length=32 {
      G-5    2  i6
      G-5    2
      G-5    2
      G-5    2
      G-5    2
      G-5    2
      F-5    2
      G-5    2
      G-5    2
      F-5    2
      G-5    4
      G-5    2
      G-5    2
      F-5    2
      F-5    2
    }
    pattern 31 length=32 {
      G#8    8  i8
      G#8   16  tie
      G#3    4  i13
      G#3    4
    }
  }
  voice 3 {
    orderlist: 1 1 2 3 1 1 2 3 1 1 2 3 4 4 5 6 1 1 2 3 4 4 5 6 1 11 3 1 1 1 2 3 1 1 2 3 1 1 11 11 13 13 14 14 13 13 14 14 11 11 11 11 3 3 3 3 25 25 25 25 25 25 25 25 1 1 11 11 25 25 25 25 1 11 25 25 1 1 11 11 1 1 11 11 1 1 11 11 1 1 11 11 1 1 11 11 13 13 14 14 13 13 14 14 13 13 14 14 25 25 31 1 11 25 11 11 25 3 3 3 3 25 31 loop@0
    pattern 1 length=32 {
      A-1    6  i3
      A-2    2
      A#3    4  i4
      A-1    4  i3
      A-1    8
      A#3    4  i4
      G-2    2  i3
      A-2    2
    }
    pattern 2 length=32 {
      A#1    6  i3
      A#2    2
      A#3    4  i4
      A#1    4  i3
      A#1    8
      A#3    4  i4
      A-2    2  i3
      A#2    2
    }
    pattern 3 length=32 {
      E-1    6  i3
      E-2    2
      A#3    4  i4
      E-1    4  i3
      E-1    8
      A#3    4  i4
      D-2    2  i3
      E-2    2
    }
    pattern 4 length=32 {
      C-2    6  i3
      C-3    2
      A#3    4  i4
      C-2    4  i3
      C-2    8
      A#3    4  i4
      A#2    2  i3
      C-3    2
    }
    pattern 5 length=32 {
      C#2    6  i3
      C#3    2
      A#3    4  i4
      C#2    4  i3
      C#2    8
      A#3    4  i4
      C-3    2  i3
      C#3    2
    }
    pattern 6 length=32 {
      G-1    6  i3
      G-2    2
      A#3    4  i4
      G-1    4  i3
      G-1    8
      A#3    4  i4
      E-2    2  i3
      E-2    2
    }
    pattern 11 length=32 {
      D-2    6  i3
      D-3    2
      A#3    4  i4
      D-2    4  i3
      D-2    8
      A#3    4  i4
      C-3    2  i3
      D-3    2
    }
    pattern 13 length=32 {
      F#1    6  i3
      F#2    2
      A#3    4  i4
      F#1    4  i3
      F#1    8
      A#3    4  i4
      E-2    2  i3
      F#2    2
    }
    pattern 14 length=32 {
      C#2    6  i3
      C#3    2
      A#3    4  i4
      C#2    4  i3
      C#2    8
      A#3    4  i4
      B-2    2  i3
      C#3    2
    }
    pattern 25 length=32 {
      D#3    2  i6
      D#3    2
      D#3    2
      D#3    2
      G#3    4  i13
      C#3    2  i6
      D#3    4
      C#3    2
      D#3    2
      D#3    2
      B-3    4  i13
      G#3    4
    }
    pattern 31 length=32 {
      G#8    8  i8
      G#8   16  tie
      G#3    4  i13
      G#3    4
    }
  }
}

subtune 1 music {
  tempo: 4
  voice 1 {
    orderlist: 36 37 36 38 39 36 38 40 40 loop@0
    pattern 36 length=96 {
      C#5   24  i9
      B-4    8
      D-5    4
      C#5    8
      B-4    8
      C#5   12
      A-4   24
      A-4    8
    }
    pattern 37 length=32 {
      A-4    4
      G#4    8
      F#4   12
      G#4    4
      A-4    4
    }
    pattern 38 length=32 {
      A-4    4
      G#4    8
      F#4    8
      E-4   12
    }
    pattern 39 length=128 {
      E-4   24
      F#4    4
      A-4    4
      A-4    8
      G#4   16
      A-4    4
      B-4    4
      C#5    8
      B-4   16
      C#5    4
      D-5    4
      D-5    8
      C#5    8
      B-4    8
      A-4    8
    }
    pattern 40 length=128 {
      A-4   32
      A-4    4  tie
      D-4    4
      E-4    4
      D-4    4
      A-4    4
      G#4    4
      E-4    4
      B-4    4
      A-4   32
      A-4    4  tie
      D-4    4
      E-4    4
      D-4    4
      A-4    4
      G#4    4
      E-4    4
      D-4    4
    }
  }
  voice 2 {
    orderlist: 41 loop@0
    pattern 41 length=32 {
      A-3    4  i10
      E-4    4
      A-4    4
      E-4    4
      A-4    4
      A-4    4
      E-4    4
      A-4    4
    }
  }
  voice 3 {
    orderlist: 32 32 34 33 32 35 35 35 35 loop@0
    pattern 32 length=128 {
      A-1    8  i3
      A#3    4  i4
      A-1    4  i3
      A-1    8
      A#3    4  i4
      A-1    4  i3
      G-1    8
      A#3    4  i4
      G-1    4  i3
      G-1    8
      A#3    4  i4
      G-1    4  i3
      D-2    8
      A#3    4  i4
      D-2    4  i3
      D-2    8
      A#3    4  i4
      D-2    4  i3
      E-2    8
      A#3    4  i4
      E-2    4  i3
      E-2    8
      A#3    4  i4
      E-2    4  i3
    }
    pattern 33 length=64 {
      D-2    8
      A#3    4  i4
      D-2    4  i3
      D-2    8
      A#3    4  i4
      D-2    4  i3
      E-2    8
      A#3    4  i4
      E-2    4  i3
      E-2    8
      A#3    4  i4
      E-2    4  i3
    }
    pattern 34 length=64 {
      F#2    8
      A#3    4  i4
      F#2    4  i3
      F#2    8
      A#3    4  i4
      F#2    4  i3
      C#2    8
      A#3    4  i4
      C#2    4  i3
      C#2    8
      A#3    4  i4
      C#2    4  i3
    }
    pattern 35 length=64 {
      A-1    8
      A#3    4  i4
      A-1    4  i3
      A-1    8
      A#3    4  i4
      A-1    4  i3
      D-2    8
      A#3    4  i4
      D-2    4  i3
      E-2    8
      A#3    4  i4
      E-2    4  i3
    }
  }
}

subtune 2 music {
  tempo: 3
  voice 1 {
    orderlist: 42 0 stop
    pattern 0 length=32 {
      C-0   32  tie
    }
    pattern 42 length=96 {
      E-4    2  i11
      E-4    2
      E-4    4
      E-4    4
      E-4    4
      G-4    8
      A-4    8
      E-4    2
      E-4    2
      E-4    4
      E-4    4
      E-4    4
      G-4    8
      A-4    8
      A-4    2  tie
      B-4    2
      B-4    4
      B-4    4
      C#5    4
      B-4   16
    }
  }
  voice 2 {
    orderlist: 43 0 stop
    pattern 0 length=32 {
      C-0   32  tie
    }
    pattern 43 length=96 {
      C#4    2  i11
      C#4    2
      C#4    4
      C#4    4
      C#4    4
      E-4    8
      F#4    8
      C#4    2
      C#4    2
      C#4    4
      C#4    4
      C#4    4
      E-4    8
      F#4    8
      F#4    2  tie
      G#4    2
      G#4    4
      G#4    4
      A#4    4
      G#4   16
    }
  }
  voice 3 {
    orderlist: 44 0 stop
    pattern 0 length=32 {
      C-0   32  tie
    }
    pattern 44 length=96 {
      A-3    2  i11
      A-3    2
      A-3    4
      A-3    4
      A-3    4
      C-4    8
      D-4    8
      A-3    2
      A-3    2
      A-3    4
      A-3    4
      A-3    4
      C-4    8
      D-4    8
      D-4    2  tie
      E-4    2
      E-4    4
      E-4    4
      F#4    4
      E-4   16
    }
  }
}

subtune 3 sfx {
  v1: $24 $80 $11 $11 $7C $30
  v2: $00 $80 $08 $15 $4C $00
  sweep: start=$50 end=$18 rate=0 direction=down
  v2_offset: $11
}

subtune 4 sfx {
  v1: $58 $80 $11 $81 $0A $30
  v2: $00 $80 $08 $15 $0A $90
  sweep: start=$38 end=$58 rate=0 direction=up
  v2_offset: $00
  flags: skip_v1
}

subtune 5 sfx {
  v1: $0F $80 $11 $81 $0A $10
  v2: $00 $80 $08 $81 $0A $10
  sweep: start=$3F end=$27 rate=1 direction=down
  v2_offset: $20
  flags: skip_v1
}

subtune 6 sfx {
  v1: $50 $00 $08 $41 $0D $40
  v2: $0F $80 $08 $15 $0D $40
  sweep: start=$6F end=$00 rate=1 direction=down
  v2_offset: $03
}

subtune 7 sfx {
  v1: $00 $80 $08 $41 $00 $C0
  v2: $00 $80 $08 $41 $00 $C0
  sweep: start=$5F end=$30 rate=1 direction=down
  v2_offset: $04
  flags: toggle_v1 toggle_v2
}

subtune 8 sfx {
  v1: $01 $00 $00 $51 $0F $F0
  v2: $02 $00 $00 $57 $0F $F0
  sweep: start=$33 end=$5F rate=3 direction=up
  v2_offset: $00
  flags: skip_both
}

subtune 9 sfx {
  v1: $02 $00 $00 $51 $0F $F0
  v2: $03 $00 $00 $57 $0F $F0
  sweep: start=$00 end=$28 rate=6 direction=up
  v2_offset: $00
  flags: skip_v1
}

subtune 10 sfx {
  v1: $07 $80 $02 $41 $00 $FF
  v2: $27 $00 $04 $43 $00 $FF
  sweep: start=$00 end=$4F rate=1 direction=up
  v2_offset: $00
  flags: skip_v1
}

subtune 11 sfx {
  v1: $08 $00 $01 $81 $0C $40
  v2: $04 $00 $08 $15 $0C $00
  sweep: start=$30 end=$10 rate=2 direction=down
  v2_offset: $04
}

subtune 12 sfx {
  v1: $18 $00 $08 $81 $07 $00
  v2: $01 $00 $02 $85 $06 $00
  sweep: start=$00 end=$48 rate=1 direction=up
  v2_offset: $05
  flags: toggle_v1 toggle_v2 skip_v1
}

subtune 13 sfx {
  v1: $14 $00 $08 $81 $0C $00
  v2: $01 $00 $01 $43 $0A $00
  sweep: start=$30 end=$08 rate=0 direction=down
  v2_offset: $25
  flags: skip_v1
}

subtune 14 sfx {
  v1: $20 $80 $08 $81 $0B $00
  v2: $27 $00 $02 $15 $0A $00
  sweep: start=$5F end=$27 rate=0 direction=down
  v2_offset: $00
  flags: skip_v1
}

subtune 15 sfx {
  v1: $14 $80 $03 $41 $0D $00
  v2: $10 $00 $06 $41 $0D $00
  sweep: start=$26 end=$53 rate=2 direction=up
  v2_offset: $06
}

subtune 16 sfx {
  v1: $18 $80 $08 $41 $09 $20
  v2: $37 $00 $02 $15 $09 $10
  sweep: start=$00 end=$26 rate=2 direction=up
  v2_offset: $0E
  flags: toggle_v1 toggle_v2 skip_both
}

subtune 17 sfx {
  v1: $0A $80 $08 $81 $0A $00
  v2: $17 $A0 $02 $81 $0A $00
  sweep: start=$36 end=$4F rate=2 direction=up
  v2_offset: $00
  flags: skip_both
}

subtune 18 sfx {
  v1: $09 $80 $08 $81 $09 $00
  v2: $02 $00 $02 $81 $09 $00
  sweep: start=$30 end=$07 rate=0 direction=down
  v2_offset: $00
  flags: skip_v1
}
