version: 2
engine: companion

psid {
  title:      "Up, up & Away!"
  author:     "Rob Hubbard"
  released:   "1984 Starcade"
  clock:      PAL
  sid:        6581
  start_song: 1
}

params {
  freq_table_base: $1000
  instr_base: $1000
  instr_count: 15
}

init {
  voice 1 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i1  slide_v: $00 }
  voice 2 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i2  slide_v: $00 }
  voice 3 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i3  slide_v: $00 }
}

instrument 1 {
  waveform: $40
  loop:     0
  pwm:      mode=none speed=0 init=$0C00 min_hi=0 max_hi=0
  adsr:     $07 $85
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 2 {
  waveform: $40
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $07 $85
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 3 {
  waveform: $40
  loop:     0
  pwm:      mode=none speed=0 init=$0100 min_hi=0 max_hi=0
  adsr:     $09 $57
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 4 {
  waveform: $10
  loop:     0
  pwm:      mode=none speed=0 init=$0C00 min_hi=0 max_hi=0
  adsr:     $00 $F5
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 5 {
  waveform: $10
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $00 $F5
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 6 {
  waveform: $40
  loop:     0
  pwm:      mode=none speed=0 init=$0400 min_hi=0 max_hi=0
  adsr:     $07 $37
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 7 {
  waveform: $40
  loop:     0
  pwm:      mode=none speed=0 init=$0C00 min_hi=0 max_hi=0
  adsr:     $07 $85
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 8 {
  waveform: $40
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $07 $85
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 9 {
  waveform: $40
  loop:     0
  pwm:      mode=none speed=0 init=$0100 min_hi=0 max_hi=0
  adsr:     $09 $67
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 10 {
  waveform: $40
  loop:     0
  pwm:      mode=none speed=0 init=$0A00 min_hi=0 max_hi=0
  adsr:     $29 $85
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 11 {
  waveform: $20
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $27 $45
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 12 {
  waveform: $20
  loop:     0
  pwm:      mode=none speed=0 init=$0900 min_hi=0 max_hi=0
  adsr:     $27 $47
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 13 {
  waveform: $40
  loop:     0
  pwm:      mode=none speed=0 init=$0700 min_hi=0 max_hi=0
  adsr:     $07 $85
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 14 {
  waveform: $10
  loop:     0
  pwm:      mode=none speed=0 init=$0800 min_hi=0 max_hi=0
  adsr:     $09 $F5
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

instrument 15 {
  waveform: $40
  loop:     0
  pwm:      mode=none speed=0 init=$0980 min_hi=0 max_hi=0
  adsr:     $09 $57
  arp:      offsets=[0] period=1
  vibrato:  scale=0
  envelope: gate_off_delta=0 adsr_zero_delta=0
}

subtune 0 music {
  tempo: 1
  params {
    filter_cutoff_hi: 0
    gate_off_tick: 9
    init_pwm_ctr: 255
    init_pwm_ctr_2: 255
    init_tempo_counter: 12
    note_load_tick: 13
    v1_pad_byte: 255
    v1_pad_count: 8
    v2_pad_byte: 255
    v2_pad_count: 8
    v3_pad_byte: 0
    v3_pad_count: 8
    vol_filter: 15
  }
  init {
    voice 1 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i1  slide_v: $00 }
    voice 2 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i2  slide_v: $00 }
    voice 3 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i3  slide_v: $00 }
  }
  voice 1 {
    orderlist: 1 stop
    pattern 1 length=199 {
      D-4    1
      D-4    1  fx:early_release
      D-4    1
      G-4    1
      G-4    1
      A-4    1
      A-4    1  fx:early_release
      B-4    1
      B-4    1
      B-4    1
      B-4    1
      B-4    1  fx:early_release
      B-4    1
      B-4    1  fx:early_release
      B-4    1
      B-4    1  fx:early_release
      B-4    1
      C-5    1
      C-5    1
      C-5    1
      A-4    1
      A-4    1
      G-4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      F-4    1
      F-4    1  fx:early_release
      F-4    1
      A#4    1
      A#4    1
      C-5    1
      C-5    1  fx:early_release
      D-5    1
      D-5    1
      D-5    1
      D-5    1
      D-5    1
      ---    1  fx:early_release
      D-5    1  fx:early_release
      D-5    1
      D-5    1  fx:early_release
      D-5    1
      D#5    1
      D#5    1
      D#5    1
      C-5    1
      C-5    1
      A#4    1
      C-5    1
      C-5    1
      C-5    1
      C-5    1
      C-5    1  fx:early_release
      C#4    1
      C#4    1  fx:early_release
      D#4    1
      D#4    1  fx:early_release
      F-4    1
      F-4    1
      F-4    1  fx:early_release
      F-4    1  fx:early_release
      F-4    1  fx:early_release
      F-4    1
      F-4    1
      F-4    1  fx:early_release
      F-4    1
      F-4    1  fx:early_release
      F-4    1
      F#4    1
      F#4    1
      F#4    1
      F-4    1
      F-4    1  fx:early_release
      F-4    1
      F-4    1
      F#4    1
      C#4    1
      C#4    1
      C#4    1
      C#4    1
      C#4    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      D#4    1
      D#4    1
      F-4    1
      F#4    1
      F#4    1
      F#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      C#4    1  fx:early_release
      C#4    1
      C#4    1
      C#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      E-4    1
      E-4    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      A-4    1  fx:early_release
      A-4    1
      B-4    1
      E-5    1
      E-5    1
      B-4    1
      C#5    1
      C#5    1  fx:early_release
      C#5    1
      C#5    1  fx:early_release
      C#5    1
      C#5    1  fx:early_release
      C#5    1
      D-5    1
      D-5    1
      B-4    1
      B-4    1
      B-4    1
      A-4    1
      A-4    1
      B-4    1
      C#5    1
      C#5    1
      A-4    1
      A-4    1
      A-4    1
      E-4    1
      E-4    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1  fx:early_release
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
      E-5    1
    }
  }
  voice 2 {
    orderlist: 1 stop
    pattern 1 length=199 {
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      ---    1  fx:early_release
      G-4    1
      G-4    1
      G-4    1
      G-4    1
      G-4    1
      F#4    1
      F#4    1
      F#4    1
      F#4    1
      F-4    1
      F-4    1
      F-4    1
      F-4    1
      F-4    1
      F-4    1
      F-4    1
      F-4    1
      E-4    1
      E-4    1
      E-4    1
      E-4    1
      D#4    1
      D#4    1
      D#4    1
      D#4    1
      D-4    1
      D-4    1
      D-4    1
      D-4    1
      D-4    1
      D-4    1
      ---    1  fx:early_release
      A#4    1
      A#4    1
      A#4    1
      A#4    1
      A#4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      G#4    1
      G#4    1
      G#4    1
      G#4    1
      G-4    1
      G-4    1
      G-4    1
      F#4    1
      F#4    1
      F#4    1
      F#4    1
      F#4    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      C#4    1
      C#4    1
      C#4    1
      C#4    1
      C-4    1
      C-4    1
      C-4    1
      C-4    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      A#3    1
      A#3    1
      A#3    1
      A#3    1
      A#3    1
      A#3    1
      A#3    1
      A#3    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      B-3    1
      B-3    1
      C#4    1
      D#4    1
      D#4    1
      D#4    1
      F-4    1
      F-4    1
      F-4    1
      D#4    1
      F-4    1
      D#4    1
      C#4    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      F-4    1
      F-4    1
      F-4    1
      D#4    1
      F-4    1
      D#4    1
      C#4    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      C#4    1
      D-4    1
      C#4    1
      C#4    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      C#4    1
      C#4    1
      C#4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      G#4    1
      G#4    1
      G-4    1
      G-4    1
      F#4    1
      F#4    1
      F#4    1
      F#4    1
      F#4    1
      F#4    1
      F#4    1
      F#4    1
      F-4    1
      F-4    1
      F-4    1
      F-4    1
      F-4    1
      F-4    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      C#5    1
      C#5    1
      C#5    1  fx:early_release
      C#5    1  fx:early_release
      C#5    1  fx:early_release
      C#5    1
      C#5    1
      ---    1  fx:early_release
      B-4    1
      B-4    1  fx:early_release
      A-4    1
      A-4    1
      A-4    1
      ---    1  fx:early_release
      B-4    1
      B-4    1
      C#5    1
      C#5    1
      C#5    1  fx:early_release
      C#5    1  fx:early_release
      C#5    1  fx:early_release
      C#5    1
      C#5    1
      ---    1  fx:early_release
      B-4    1
      B-4    1  fx:early_release
      A-4    1
      A-4    1
      A-4    1
      ---    1  fx:early_release
      B-4    1
      B-4    1  fx:early_release
      C#5    1
      C#5    1
      C#5    1
      C#5    1
      C#5    1
      C#5    1
      C#5    1
    }
  }
  voice 3 {
    orderlist: 1 stop
    pattern 1 length=199 {
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-3    1  fx:early_release
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-3    1  fx:early_release
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-3    1  fx:early_release
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-3    1  fx:early_release
      G-2    1  fx:early_release
      F-2    1  fx:early_release
      F-2    1  fx:early_release
      F-3    1  fx:early_release
      F-2    1  fx:early_release
      F-2    1  fx:early_release
      F-2    1  fx:early_release
      F-3    1  fx:early_release
      F-2    1  fx:early_release
      F-2    1  fx:early_release
      F-2    1  fx:early_release
      F-3    1  fx:early_release
      F-2    1  fx:early_release
      F-2    1  fx:early_release
      F-2    1  fx:early_release
      G-3    1  fx:early_release
      A-2    1  fx:early_release
      A#2    1  fx:early_release
      A#2    1  fx:early_release
      A#3    1  fx:early_release
      A#2    1  fx:early_release
      A#2    1  fx:early_release
      A#2    1  fx:early_release
      A#3    1  fx:early_release
      A#2    1  fx:early_release
      A#2    1  fx:early_release
      A#2    1  fx:early_release
      A#3    1  fx:early_release
      A#2    1  fx:early_release
      A#2    1  fx:early_release
      A#2    1  fx:early_release
      A#3    1  fx:early_release
      A#2    1  fx:early_release
      G#2    1  fx:early_release
      G#2    1  fx:early_release
      G#3    1  fx:early_release
      G#2    1  fx:early_release
      G#2    1  fx:early_release
      G#2    1  fx:early_release
      G#3    1  fx:early_release
      G#2    1  fx:early_release
      G#2    1  fx:early_release
      G#2    1  fx:early_release
      G#3    1  fx:early_release
      G#2    1  fx:early_release
      G#2    1  fx:early_release
      F#2    1  fx:early_release
      F-3    1  fx:early_release
      D#2    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      C#3    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      C#3    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      C#3    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      D#2    1  fx:early_release
      F-3    1  fx:early_release
      G#2    1  fx:early_release
      F#2    1  fx:early_release
      F#2    1  fx:early_release
      F#3    1  fx:early_release
      F#2    1  fx:early_release
      F#2    1  fx:early_release
      F-2    1  fx:early_release
      D#3    1  fx:early_release
      C#2    1  fx:early_release
      B-1    1  fx:early_release
      B-1    1  fx:early_release
      B-2    1  fx:early_release
      B-1    1  fx:early_release
      B-1    1  fx:early_release
      B-1    1  fx:early_release
      B-2    1  fx:early_release
      B-1    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      C#3    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      C#3    1  fx:early_release
      C#2    1  fx:early_release
      G#2    1  fx:early_release
      G#2    1  fx:early_release
      G#3    1  fx:early_release
      G#2    1  fx:early_release
      G#2    1  fx:early_release
      G#2    1  fx:early_release
      G#2    1  fx:early_release
      G#2    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      C#3    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      C#2    1  fx:early_release
      C#3    1  fx:early_release
      C#2    1  fx:early_release
      E-2    1  fx:early_release
      E-2    1  fx:early_release
      E-3    1  fx:early_release
      E-2    1  fx:early_release
      E-2    1  fx:early_release
      E-2    1  fx:early_release
      F#3    1  fx:early_release
      G#2    1  fx:early_release
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      A-3    1  fx:early_release
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      A-3    1  fx:early_release
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      A-3    1  fx:early_release
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      A-3    1  fx:early_release
      A-2    1  fx:early_release
      D-2    1  fx:early_release
      D-2    1  fx:early_release
      D-3    1  fx:early_release
      D-2    1  fx:early_release
      D-2    1  fx:early_release
      D-2    1  fx:early_release
      E-3    1  fx:early_release
      F#2    1  fx:early_release
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-3    1  fx:early_release
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-3    1  fx:early_release
      G-2    1  fx:early_release
      A-2    1
      A-2    1
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      A-2    1
      A-2    1
      ---    1  fx:early_release
      G-2    1
      G-2    1  fx:early_release
      F-2    1
      F-2    1
      F-2    1
      ---    1  fx:early_release
      G-2    1
      G-2    1
      A-2    1
      A-2    1
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      A-2    1
      A-2    1
      ---    1  fx:early_release
      G-2    1
      G-2    1  fx:early_release
      F-2    1
      F-2    1
      F-2    1
      ---    1  fx:early_release
      G-2    1
      G-2    1  fx:early_release
      A-2    1
      A-2    1
      A-2    1
      A-2    1
      A-2    1
      A-2    1
      A-2    1
    }
  }
}

subtune 1 music {
  tempo: 1
  params {
    filter_cutoff_hi: 255
    gate_off_tick: 9
    init_pwm_ctr: 255
    init_pwm_ctr_2: 255
    init_tempo_counter: 11
    note_load_tick: 12
    v1_pad_byte: 0
    v1_pad_count: 15
    v2_pad_byte: 0
    v2_pad_count: 15
    v3_pad_byte: 0
    v3_pad_count: 15
    vol_filter: 15
  }
  init {
    voice 1 { ctrl: $10  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i4  slide_v: $00 }
    voice 2 { ctrl: $10  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i5  slide_v: $00 }
    voice 3 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i6  slide_v: $00 }
  }
  voice 1 {
    orderlist: 1 stop
    pattern 1 length=48 {
      C-5    1
      C-5    1  fx:early_release
      C-5    1
      C-5    1
      E-5    1
      E-5    1
      E-4    1  fx:early_release
      E-4    1  fx:early_release
      F-4    1
      F-4    1
      A-4    1
      A-4    1  fx:early_release
      A-4    1
      A-4    1  fx:early_release
      A#4    1
      A#4    1
      D-5    1
      D-5    1
      D-4    1
      D-4    1
      D#4    1
      D#4    1
      D#4    1
      D#4    1  fx:early_release
      D#4    1
      D#4    1
      G#4    1
      G#4    1
      C-5    1
      C-5    1
      C-4    1  fx:early_release
      C-4    1  fx:early_release
      C#4    1
      C#4    1
      F-4    1
      F-4    1  fx:early_release
      F-4    1
      F-4    1  fx:early_release
      B-3    1
      B-3    1
      D-4    1
      D-4    1
      F-4    1
      F-4    1
      E-4    1
      E-4    1
      E-4    1
      E-4    1
    }
  }
  voice 2 {
    orderlist: 1 stop
    pattern 1 length=48 {
      E-5    1
      E-5    1  fx:early_release
      E-5    1
      E-5    1
      G-5    1
      G-5    1
      G-4    1  fx:early_release
      G-4    1  fx:early_release
      A-4    1
      A-4    1
      C-5    1
      C-5    1  fx:early_release
      C-5    1
      C-5    1  fx:early_release
      D-5    1
      D-5    1
      F-5    1
      F-5    1
      F-4    1
      F-4    1
      G-4    1
      G-4    1
      G-4    1
      G-4    1  fx:early_release
      G-4    1
      G-4    1
      C-5    1
      C-5    1
      D#5    1
      D#5    1
      D#4    1  fx:early_release
      D#4    1  fx:early_release
      F-4    1
      F-4    1
      G#4    1
      G#4    1  fx:early_release
      G#4    1
      G#4    1  fx:early_release
      G-4    1
      G-4    1
      B-4    1
      B-4    1
      D-5    1
      D-5    1
      C-5    1
      C-5    1
      C-5    1
      C-5    1
    }
  }
  voice 3 {
    orderlist: 1 stop
    pattern 1 length=48 {
      ---    1  fx:early_release
      ---    1  fx:early_release
      C-3    1
      C-3    1
      C-3    1
      C-3    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      F-2    1
      F-2    1
      F-2    1
      F-2    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      A#2    1
      A#2    1
      A#2    1
      A#2    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      D#3    1
      D#3    1
      D#3    1
      D#3    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      G#2    1
      G#2    1
      G#2    1
      G#2    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      C#3    1
      C#3    1
      C#3    1
      C#3    1
      ---    1  fx:early_release
      ---    1  fx:early_release
      G-2    1
      G-2    1  fx:early_release
      G-2    1
      G-2    1  fx:early_release
      B-2    1
      B-2    1  fx:early_release
      C-3    1
      C-3    1
      C-3    1
      C-3    1
    }
  }
}

subtune 2 music {
  tempo: 1
  params {
    filter_cutoff_hi: 70
    gate_off_tick: 6
    init_pwm_ctr: 0
    init_pwm_ctr_2: 0
    init_tempo_counter: 11
    note_load_tick: 12
    v1_pad_byte: 0
    v1_pad_count: 0
    v2_pad_byte: 0
    v2_pad_count: 0
    v3_pad_byte: 0
    v3_pad_count: 0
    vol_filter: 31
  }
  init {
    voice 1 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i7  slide_v: $00 }
    voice 2 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i8  slide_v: $00 }
    voice 3 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i9  slide_v: $00 }
  }
  voice 1 {
    orderlist: 1 stop
    pattern 1 length=31 {
      G-4    1
      G-4    1
      G-4    1
      G-4    1  fx:early_release
      G-4    1
      G-4    1
      G-4    1
      F#4    1  fx:early_release
      G-4    1  fx:early_release
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1
      A-4    1  fx:early_release
      G-4    1  fx:early_release
      A-4    1
      A-4    1  fx:early_release
      G-4    1  fx:early_release
      A-4    1  fx:early_release
      G-4    1
      G-4    1  fx:early_release
      F#4    1  fx:early_release
      F-4    1
      F-4    1
      F-4    1  fx:early_release
      B-4    1  fx:early_release
      C-5    1
      C-5    1
      C-5    1
    }
  }
  voice 2 {
    orderlist: 1 stop
    pattern 1 length=31 {
      E-4    1
      E-4    1
      E-4    1
      E-4    1  fx:early_release
      E-4    1
      E-4    1
      E-4    1
      D#4    1  fx:early_release
      E-4    1  fx:early_release
      F-4    1
      F-4    1
      F-4    1
      F-4    1
      F-4    1
      F-4    1
      F-4    1  fx:early_release
      E-4    1  fx:early_release
      F-4    1
      F-4    1  fx:early_release
      E-4    1  fx:early_release
      F-4    1  fx:early_release
      E-4    1
      E-4    1  fx:early_release
      D#4    1  fx:early_release
      D-4    1
      D-4    1
      D-4    1  fx:early_release
      F-4    1  fx:early_release
      E-4    1
      E-4    1
      E-4    1
    }
  }
  voice 3 {
    orderlist: 1 stop
    pattern 1 length=31 {
      C-2    1
      C-4    1  fx:early_release
      C-2    1
      C-4    1  fx:early_release
      C-2    1
      C-4    1  fx:early_release
      C-2    1
      C-4    1  fx:early_release
      C-2    1
      C-4    1  fx:early_release
      C-2    1
      C-4    1  fx:early_release
      C-2    1
      C-4    1  fx:early_release
      C-2    1
      C-4    1  fx:early_release
      C-2    1
      C-4    1  fx:early_release
      E-2    1
      E-3    1  fx:early_release
      F-2    1
      F-3    1  fx:early_release
      F#2    1
      F#3    1  fx:early_release
      G-2    1
      G-3    1  fx:early_release
      G-2    1
      G-3    1  fx:early_release
      C-2    1
      C-2    1
      C-2    1
    }
  }
}

subtune 3 music {
  tempo: 1
  params {
    filter_cutoff_hi: 255
    gate_off_tick: 3
    init_pwm_ctr: 255
    init_pwm_ctr_2: 255
    init_tempo_counter: 5
    note_load_tick: 6
    v1_pad_byte: 0
    v1_pad_count: 0
    v2_pad_byte: 0
    v2_pad_count: 0
    v3_pad_byte: 0
    v3_pad_count: 0
    vol_filter: 15
  }
  init {
    voice 1 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i10  slide_v: $00 }
    voice 2 { ctrl: $20  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i11  slide_v: $00 }
    voice 3 { ctrl: $20  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i12  slide_v: $00 }
  }
  voice 1 {
    orderlist: 1 stop
    pattern 1 length=31 {
      A#3    1
      A#3    1
      A#3    1
      A#3    1  fx:early_release
      A#3    1
      A#3    1
      A#3    1  fx:early_release
      A#3    1  fx:early_release
      A#3    1
      A#3    1
      A#3    1
      A#3    1  fx:early_release
      C#4    1
      C#4    1
      C#4    1  fx:early_release
      C-4    1  fx:early_release
      C-4    1
      C-4    1
      C-4    1  fx:early_release
      A#3    1  fx:early_release
      A#3    1
      A#3    1
      A#3    1  fx:early_release
      A#3    1  fx:early_release
      A#3    1
      A#3    1
      A#3    1
      A#3    1
      A#3    1
      A#3    1
      A#3    1
    }
  }
  voice 2 {
    orderlist: 1 stop
    pattern 1 length=31 {
      F-3    1
      F-3    1
      F-3    1
      F-3    1  fx:early_release
      F#3    1
      F#3    1
      F#3    1
      F#3    1  fx:early_release
      F-3    1
      F-3    1
      F-3    1
      F-3    1  fx:early_release
      F#3    1
      F#3    1
      F#3    1
      F#3    1  fx:early_release
      F-3    1
      F-3    1
      F-3    1
      F-3    1  fx:early_release
      F#3    1
      F#3    1
      F#3    1
      F#3    1  fx:early_release
      F-3    1
      F-3    1
      F-3    1
      F-3    1
      F-3    1
      F-3    1
      F-3    1
    }
  }
  voice 3 {
    orderlist: 1 stop
    pattern 1 length=31 {
      A#2    1
      A#2    1
      A#2    1
      A#2    1  fx:early_release
      A#2    1
      A#2    1
      A#2    1
      A#2    1  fx:early_release
      A#2    1
      A#2    1
      A#2    1
      A#2    1  fx:early_release
      A#2    1
      A#2    1
      A#2    1
      A#2    1  fx:early_release
      A#2    1
      A#2    1
      A#2    1
      A#2    1  fx:early_release
      A#2    1
      A#2    1
      A#2    1
      A#2    1  fx:early_release
      A#2    1
      A#2    1
      A#2    1
      A#2    1
      A#2    1
      A#2    1
      A#2    1
    }
  }
}

subtune 4 music {
  tempo: 1
  params {
    filter_cutoff_hi: 255
    gate_off_tick: 5
    init_pwm_ctr: 0
    init_pwm_ctr_2: 0
    init_tempo_counter: 8
    note_load_tick: 9
    v1_pad_byte: 0
    v1_pad_count: 0
    v2_pad_byte: 0
    v2_pad_count: 0
    v3_pad_byte: 255
    v3_pad_count: 8
    vol_filter: 15
  }
  init {
    voice 1 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i13  slide_v: $00 }
    voice 2 { ctrl: $10  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i14  slide_v: $00 }
    voice 3 { ctrl: $40  dur_field: $00  pwm_period: $00  pwm_dir: up  instr: i15  slide_v: $00 }
  }
  voice 1 {
    orderlist: 1 stop
    pattern 1 length=71 {
      B-3    1
      B-3    1
      B-3    1
      B-3    1
      C-4    1
      C-4    1
      C-4    1
      C-4    1
      D-4    1
      D-4    1
      G-4    1
      G-4    1  fx:early_release
      G-4    1
      G-4    1  fx:early_release
      G-4    1
      G-4    1
      G-4    1
      G-4    1
      F#4    1
      F#4    1
      F#4    1
      F#4    1
      G-4    1
      G-4    1
      A-4    1
      A-4    1
      E-4    1
      E-4    1  fx:early_release
      E-4    1
      E-4    1  fx:early_release
      E-4    1
      E-4    1
      E-4    1
      E-4    1
      G-4    1
      G-4    1
      G-4    1
      G-4    1
      E-4    1
      E-4    1
      F#4    1
      F#4    1  fx:early_release
      F#4    1  fx:early_release
      F#4    1  fx:early_release
      F#4    1
      F#4    1  fx:early_release
      F#4    1
      F#4    1
      F#4    1
      F#4    1
      E-4    1
      E-4    1
      E-4    1
      E-4    1
      F#4    1
      F#4    1
      G-4    1
      G-4    1  fx:early_release
      G-3    1  fx:early_release
      G-3    1  fx:early_release
      G-3    1
      G-3    1  fx:early_release
      G-3    1
      G-3    1
      G-3    1
      G-3    1
      G-3    1
      G-3    1
      G-3    1
      G-3    1
      G-3    1
    }
  }
  voice 2 {
    orderlist: 1 stop
    pattern 1 length=71 {
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      D-3    1
      G-3    1
      B-3    1
      D-4    1
      G-4    1
      B-4    1
      D-5    1
      G-5    1
      B-5    1
      G-5    1
      D-5    1
      B-4    1
      G-4    1
      D-4    1
      B-3    1
      G-3    1
      E-3    1
      A-3    1
      C#4    1
      E-4    1
      A-4    1
      C#5    1
      E-5    1
      A-5    1
      C#6    1
      A-5    1
      E-5    1
      C#5    1
      A-4    1
      E-4    1
      C#4    1
      A-3    1
      D-3    1
      F#3    1
      A-3    1
      C-4    1
      D-4    1
      F#4    1
      A-4    1
      C-5    1
      D-5    1
      F#5    1
      A-5    1
      F#5    1
      D-5    1
      A-4    1
      F#4    1
      D-4    1
      B-3    1
      B-3    1  fx:early_release
      D-3    1  fx:early_release
      D-3    1  fx:early_release
      D-3    1
      D-3    1  fx:early_release
      D-3    1
      D-3    1
      D-3    1
      D-3    1
      D-3    1
      D-3    1
      D-3    1
      D-3    1
      D-3    1
    }
  }
  voice 3 {
    orderlist: 1 stop
    pattern 1 length=71 {
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      ---    1  fx:early_release
      G-2    1
      G-2    1
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      D-2    1
      D-2    1  fx:early_release
      E-2    1
      E-2    1  fx:early_release
      G-2    1
      G-2    1
      G-2    1
      G-2    1  fx:early_release
      D-2    1
      D-2    1  fx:early_release
      E-2    1
      E-2    1  fx:early_release
      A-2    1
      A-2    1
      A-2    1  fx:early_release
      A-2    1  fx:early_release
      E-2    1
      E-2    1  fx:early_release
      F#2    1
      F#2    1  fx:early_release
      A-2    1
      A-2    1
      A-2    1
      A-2    1  fx:early_release
      E-2    1
      E-2    1  fx:early_release
      F#2    1
      F#2    1  fx:early_release
      D-3    1
      D-3    1
      D-3    1  fx:early_release
      D-3    1  fx:early_release
      A-2    1
      A-2    1  fx:early_release
      B-2    1
      B-2    1  fx:early_release
      D-3    1
      D-3    1
      D-3    1
      D-3    1  fx:early_release
      A-2    1
      A-2    1  fx:early_release
      B-2    1
      B-2    1  fx:early_release
      G-2    1
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-2    1  fx:early_release
      G-2    1
      G-2    1  fx:early_release
      G-2    1
      G-2    1
      G-2    1
      G-2    1
      G-2    1
      G-2    1
      G-2    1
      G-2    1
      G-2    1
    }
  }
}
