"""emit_usf2.py — Phase 3.3 deliverable: emit USF2 instrument literals.

Serialises the decoded + interpreter-verified `InstrumentModel`s
(inst_generalize.decode_all) into a self-contained Lean file —
`CommandoInsts2_gen.lean` — holding the 13 Commando instruments as
behavioral-parameter literals.

The representation is the one the whole-song reference interpreter
(song_interp.py) validated: every melodic instruction of Commando
subtune 0 reproduced byte-exact. Phase 4's Lean `Codegen2` consumes
these literals.

The emitted file is self-contained (no imports, core Lean only) so it
type-checks directly with `lean CommandoInsts2_gen.lean`.

Usage:
    python3 -m pipelines.commando.extract.emit_usf2          # write the file
    python3 -m pipelines.commando.extract.emit_usf2 --print  # to stdout
"""

from __future__ import annotations

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))
sys.path.insert(0, ROOT)

from pipelines.commando.extract.inst_generalize import (  # noqa: E402
    InstrumentModel, decode_all)

OUT_PATH = os.path.join(ROOT, 'pipelines', 'commando', 'codegen', 'Commando',
                        'CommandoInsts2_gen.lean')

SCHEMA = '''\
/-
  CommandoInsts2_gen.lean — AUTO-GENERATED by
  pipelines/commando/extract/emit_usf2.py. Do not edit by hand.

  The 13 Commando instruments as USF2 behavioral parameters, decoded
  from the instrument table ($5591) and verified by the whole-song
  reference interpreter (pipelines/commando/extract/song_interp.py):
  every melodic instruction of Commando subtune 0 is reproduced
  byte-exact (1270/1500 frames; the rest are inst 4, the drum — Phase 5).

  Self-contained — type-checks with `lean CommandoInsts2_gen.lean`.
-/
namespace USF2Gen

/-- Triangle vibrato LFO. The codegen scales a per-semitone delta by an
    8-frame triangle and applies it once the note's duration reaches
    `onsetDur` ticks. -/
structure VibratoSpec where
  depth    : Nat            -- delta is (freq[p+1]-freq[p]) >> (depth+1)
  period   : Nat := 8
  onsetDur : Nat := 6
  deriving Repr

/-- Octave arpeggio: alternate `intervals` by global frame parity. -/
structure ArpSpec where
  intervals : List Int := [0, 12]
  stepEvery : Nat := 1
  deriving Repr

/-- Pulse-width modulation. The pw accumulator is per-instrument shared
    state (every voice playing the instrument advances it). -/
inductive PwMode where
  | linear        (speed : UInt8)
  | bidirectional (period step loBound hiBound : UInt8)
  deriving Repr

structure PwmSpec where
  mode   : PwMode
  seedLo : UInt8            -- song-start pw_lo / pw_hi (table seed)
  seedHi : UInt8
  deriving Repr

/-- One Commando instrument as USF2 behavioral parameters.

    Per frame the engine applies, in order: the note-start constant
    block (frame 0 only), vibrato, PWM, skydive (`freqSlide`), and
    arpeggio; plus the hard-restart block one tick before note end. -/
structure USFInstrument where
  initCtrl  : UInt8
  initPwLo  : UInt8
  initPwHi  : UInt8
  initAd    : UInt8
  initSr    : UInt8
  hrCtrl    : UInt8                    -- = initCtrl &&& 0xFE
  vibrato   : Option VibratoSpec := none
  freqSlide : Bool := false            -- skydive
  incBy2    : Bool := false
  arpeggio  : Option ArpSpec := none
  pwm       : Option PwmSpec := none
  deriving Repr

'''


def _vib(v) -> str:
    return f'some {{ depth := {v.depth} }}'


def _arp(a) -> str:
    ivs = ', '.join(str(x) for x in a.intervals)
    return f'some {{ intervals := [{ivs}] }}'


def _pwm(p) -> str:
    if p.mode == 'linear':
        mode = f'.linear 0x{p.speed:02X}'
    else:
        mode = (f'.bidirectional 0x{p.period:02X} 0x{p.step:02X} '
                f'0x{p.lo_bound:02X} 0x{p.hi_bound:02X}')
    return (f'some {{ mode := {mode}, '
            f'seedLo := 0x{p.seed_lo:02X}, seedHi := 0x{p.seed_hi:02X} }}')


def emit_instrument(m: InstrumentModel) -> str:
    fields = [
        f'initCtrl := 0x{m.init_ctrl:02X}',
        f'initPwLo := 0x{m.init_pw_lo:02X}',
        f'initPwHi := 0x{m.init_pw_hi:02X}',
        f'initAd := 0x{m.init_ad:02X}',
        f'initSr := 0x{m.init_sr:02X}',
        f'hrCtrl := 0x{m.hr_ctrl:02X}',
    ]
    if m.vibrato:
        fields.append(f'vibrato := {_vib(m.vibrato)}')
    if m.freq_slide:
        fields.append('freqSlide := true')
    if m.inc_by2:
        fields.append('incBy2 := true')
    if m.arpeggio:
        fields.append(f'arpeggio := {_arp(m.arpeggio)}')
    if m.pwm:
        fields.append(f'pwm := {_pwm(m.pwm)}')
    return '{ ' + ',\n    '.join(fields) + ' }'


def emit(models: list[InstrumentModel]) -> str:
    lines = [SCHEMA, 'def commandoInstruments : List USFInstrument := [']
    for i, m in enumerate(models):
        comma = ',' if i < len(models) - 1 else ''
        lines.append(f'  -- inst {i}  ({m.summary()})')
        lines.append('  ' + emit_instrument(m) + comma)
    lines.append(']')
    lines.append('')
    lines.append('end USF2Gen')
    lines.append('')
    return '\n'.join(lines)


def main(argv: list[str]) -> None:
    models = decode_all(os.path.join(
        ROOT, 'demo', 'hubbard', 'Commando_original.sid'))
    text = emit(models)
    if '--print' in argv:
        sys.stdout.write(text)
        return
    with open(OUT_PATH, 'w') as f:
        f.write(text)
    print(f'wrote {OUT_PATH}  ({len(models)} instruments, {len(text)} bytes)')


if __name__ == '__main__':
    main(sys.argv[1:])
