"""Clone the Monty pipeline as a new Hubbard-classic-engine pipeline,
auto-discovering per-SID constants and patching them into the clone.

Usage:
    python tools/clone_hubbard_pipeline.py <sid_path> <pipeline_name> [music_subtunes]

Example:
    python tools/clone_hubbard_pipeline.py \\
        hvsc84/MUSICIANS/H/Hubbard_Rob/Crazy_Comets.sid \\
        crazy_comets 0,1

This copies pipelines/monty/ → pipelines/<pipeline_name>/, rewrites
Monty-specific names + paths, and patches:
  - the freq-table base address (discovered by scanning for the
    standard PAL prefix in the binary)
  - the pulsedelay / pulsedir initial bytes (read straight out of
    the binary at the DEC pulsedelay,X target address)
  - the default music subtune list

After cloning you still need to add the lakefile.lean entries (printed
at the end) and run extract / lake build.
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path


def cap(name: str) -> str:
    """snake_case → CamelCase. crazy_comets → CrazyComets."""
    return ''.join(part.capitalize() for part in name.split('_'))


def parse_psid(path: Path) -> tuple[int, bytes]:
    b = path.read_bytes()
    hl = int.from_bytes(b[6:8], 'big')
    load = int.from_bytes(b[8:10], 'big')
    payload = b[hl:]
    if load == 0:
        load = int.from_bytes(payload[:2], 'little')
        payload = payload[2:]
    return load, payload


def discover_ft_base(payload: bytes, load: int) -> int | None:
    """Find the standard PAL freq table prefix in the binary."""
    prefix = bytes([0x16, 0x01, 0x27, 0x01, 0x38, 0x01, 0x4b, 0x01])
    idx = payload.find(prefix)
    return load + idx if idx >= 0 else None


def discover_pulse_init(payload: bytes, load: int) -> tuple[list[int], list[int]] | None:
    """Find `DEC pulsedelay,X ; BPL …` and read 6 bytes at the target
    (3 pulsedelay + 3 pulsedir)."""
    for i in range(len(payload) - 5):
        if payload[i] == 0xDE and payload[i+3] == 0x10:
            addr = payload[i+1] | (payload[i+2] << 8)
            off = addr - load
            if 0 <= off < len(payload) - 6:
                return (list(payload[off:off+3]),
                        list(payload[off+3:off+6]))
    return None


def clone(sid_path: Path, pname: str, repo_root: Path,
          music_subtunes: str = '0') -> None:
    pname_cap = cap(pname)
    new_dir = repo_root / 'pipelines' / pname
    template = repo_root / 'pipelines' / 'monty'
    if new_dir.exists():
        sys.exit(f"refusing to overwrite existing {new_dir}")
    if not template.is_dir():
        sys.exit(f"template missing: {template}")

    # 1. Copy tree
    shutil.copytree(template, new_dir, ignore=shutil.ignore_patterns(
        '__pycache__', '*.pyc', 'monty.sid', '*.lock'))

    # 2. Rename Monty/ → <Name>/
    old_codegen_dir = new_dir / 'codegen' / 'Monty'
    new_codegen_dir = new_dir / 'codegen' / pname_cap
    old_codegen_dir.rename(new_codegen_dir)

    # 3. Substitute in all text files.
    # The pattern: anywhere "Monty" → "<Name>"; "MV3" → "<Name>NS" (namespace);
    # specific file paths get individually re-pointed to the new SID.
    sid_rel = sid_path.relative_to(repo_root) if sid_path.is_absolute() else sid_path
    sid_basename_no_ext = sid_path.stem  # e.g. "Crazy_Comets"

    NAMESPACE = pname_cap + 'NS'   # was MV3
    for f in new_dir.rglob('*'):
        if not f.is_file():
            continue
        if f.suffix not in {'.lean', '.py', '.md', '.toml'}:
            continue
        text = f.read_text(encoding='utf-8')
        # Specific SID filename first (before bare Monty replacement)
        text = text.replace('Monty_on_the_Run.sid', sid_path.name)
        text = text.replace('Monty_on_the_Run', sid_path.stem)
        # Output binary + lake exe name (must come before generic 'monty')
        text = text.replace('monty.sid', f'{pname}.sid')
        text = text.replace('sidgen_monty', f'sidgen_{pname}')
        # Module / package paths
        text = text.replace('pipelines.monty.', f'pipelines.{pname}.')
        text = text.replace('pipelines/monty/', f'pipelines/{pname}/')
        text = text.replace('Monty.', f'{pname_cap}.')
        text = text.replace('`Monty.', f'`{pname_cap}.')
        # Namespace (MV3 → <Name>NS)
        text = re.sub(r'\bMV3\b', NAMESPACE, text)
        # Generic free-text Monty → CapName, monty → snake_name, MONTY → UPPER
        text = text.replace('MONTY', pname.upper())
        text = text.replace('Monty', pname_cap)
        text = text.replace('monty', pname)
        f.write_text(text, encoding='utf-8')

    # 4. Rename mv3* prefixes inside SongData.lean (will be regenerated by emit_usf
    # anyway; this just makes the placeholder consistent if anyone inspects it).
    sd = new_codegen_dir / 'SongData.lean'
    if sd.exists():
        t = sd.read_text(encoding='utf-8')
        t = re.sub(r'\bmv3', f'{pname[:2]}3', t)  # mv3I0 → cc3I0 etc.; not perfect but rare to consult
        t = t.replace('montyV3', f'{pname}V3')
        sd.write_text(t, encoding='utf-8')

    # 5. Per-SID discovery: ft_base + PWM init bytes
    load, payload = parse_psid(sid_path)
    ft_base = discover_ft_base(payload, load)
    pulse_init = discover_pulse_init(payload, load)

    # Patch emit_usf.py: ft_base + default music subtunes
    emit = new_dir / 'extract' / 'emit_usf.py'
    text = emit.read_text(encoding='utf-8')
    if ft_base is not None:
        text = re.sub(r'(_FT_BASE\s*=\s*)0x[0-9A-Fa-f]+',
                      lambda m: f'{m.group(1)}0x{ft_base:04X}', text)
    # Default subtune list (was `[0]` for Monty)
    music_list = '[' + ', '.join(s.strip() for s in music_subtunes.split(',')) + ']'
    text = re.sub(r'subtune_indices: list\[int\] = \[[^\]]*\]',
                  f'subtune_indices: list[int] = {music_list}', text, count=1)
    emit.write_text(text, encoding='utf-8')

    # Patch Codegen.lean: pulsedelay/pulsedir initial bytes
    if pulse_init is not None:
        pdelay, pdir = pulse_init
        cg = new_codegen_dir / 'Codegen.lean'
        text = cg.read_text(encoding='utf-8')
        # Monty's v_pwperiod init: emitData [0, 1, 0x1D]   (3-element list)
        text = re.sub(
            r'(cb\s*:=\s*cb\.label\s+"v_pwperiod"\s*\n\s*cb\s*:=\s*cb\.emitData\s+)\[[^\]]+\]',
            f'\\1[{pdelay[0]}, {pdelay[1]}, {pdelay[2]}]',
            text)
        # v_pwdir init
        text = re.sub(
            r'(cb\s*:=\s*cb\.label\s+"v_pwdir"\s*\n\s*cb\s*:=\s*cb\.emitData\s+)\[[^\]]+\]',
            f'\\1[{pdir[0]}, {pdir[1]}, {pdir[2]}]',
            text)
        cg.write_text(text, encoding='utf-8')

    print(f"cloned pipelines/monty/ → pipelines/{pname}/")
    print(f"  ft_base discovered: ${ft_base:04X}" if ft_base else "  ft_base: NOT FOUND")
    if pulse_init:
        print(f"  pulsedelay init: {pulse_init[0]}")
        print(f"  pulsedir   init: {pulse_init[1]}")
    print(f"  default music subtunes: {music_list}")
    print(f"  codegen subdir: {new_codegen_dir.relative_to(repo_root)}")
    print(f"  namespace: {NAMESPACE}")
    print(f"  SID source: {sid_rel}")
    print(f"  output binary: {pname}.sid (at repo root)")
    print()
    print("next steps:")
    print(f"  1. Add lakefile.lean entries for {pname_cap}:")
    print(f'     lean_lib {pname_cap} where')
    print(f'       srcDir := "pipelines/{pname}/codegen"')
    print(f'       roots  := #[`{pname_cap}.SID, `{pname_cap}.Asm6502,')
    print(f'                   `{pname_cap}.PSIDFile, `{pname_cap}.USF,')
    print(f'                   `{pname_cap}.Constants, `{pname_cap}.SongData,')
    print(f'                   `{pname_cap}.Codegen, `{pname_cap}.Properties]')
    print(f'     lean_exe sidgen_{pname} where')
    print(f'       srcDir := "pipelines/{pname}/codegen"')
    print(f'       root   := `{pname_cap}.Main')
    print(f"  2. Discover ft_base for this SID (default $5428 is Commando's).")
    print(f"  3. Run extract:  python -m pipelines.{pname}.extract <subtunes>")
    print(f"  4. lake build sidgen_{pname}")
    print(f"  5. ./.lake/build/bin/sidgen_{pname}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('sid_path', type=Path, help='Original SID file path')
    ap.add_argument('pipeline_name', help='Snake_case name for the new pipeline')
    ap.add_argument('music_subtunes', nargs='?', default='0',
                    help='Comma-separated music subtune indices (default 0)')
    args = ap.parse_args(argv)
    repo_root = Path(__file__).resolve().parent.parent
    sid_path = args.sid_path if args.sid_path.is_absolute() else repo_root / args.sid_path
    if not sid_path.exists():
        sys.exit(f"SID not found: {sid_path}")
    clone(sid_path, args.pipeline_name, repo_root, args.music_subtunes)
    return 0


if __name__ == '__main__':
    sys.exit(main())
