/-
  CommandoInsts2_gen.lean — AUTO-GENERATED by
  pipelines/commando/extract/emit_usf2.py. Do not edit by hand.

  The 13 Commando instruments as USF2 behavioral parameters, decoded
  from the instrument table ($5591) and verified by the whole-song
  reference interpreter (pipelines/commando/extract/song_interp.py):
  every melodic instruction of Commando subtune 0 is reproduced
  byte-exact (1270/1500 frames; the rest are inst 4, the drum — Phase 5).

  Self-contained — type-checks with `lean CommandoInsts2_gen.lean`.
-/
namespace USF2Gen

/-- Triangle vibrato LFO. The codegen scales a per-semitone delta by an
    8-frame triangle and applies it once the note's duration reaches
    `onsetDur` ticks. -/
structure VibratoSpec where
  depth    : Nat            -- delta is (freq[p+1]-freq[p]) >> (depth+1)
  period   : Nat := 8
  onsetDur : Nat := 6
  deriving Repr

/-- Octave arpeggio: alternate `intervals` by global frame parity. -/
structure ArpSpec where
  intervals : List Int := [0, 12]
  stepEvery : Nat := 1
  deriving Repr

/-- Pulse-width modulation. The pw accumulator is per-instrument shared
    state (every voice playing the instrument advances it). -/
inductive PwMode where
  | linear        (speed : UInt8)
  | bidirectional (period step loBound hiBound : UInt8)
  deriving Repr

structure PwmSpec where
  mode   : PwMode
  seedLo : UInt8            -- song-start pw_lo / pw_hi (table seed)
  seedHi : UInt8
  deriving Repr

/-- One Commando instrument as USF2 behavioral parameters.

    Per frame the engine applies, in order: the note-start constant
    block (frame 0 only), vibrato, PWM, skydive (`freqSlide`), and
    arpeggio; plus the hard-restart block one tick before note end. -/
structure USFInstrument where
  initCtrl  : UInt8
  initPwLo  : UInt8
  initPwHi  : UInt8
  initAd    : UInt8
  initSr    : UInt8
  hrCtrl    : UInt8                    -- = initCtrl &&& 0xFE
  vibrato   : Option VibratoSpec := none
  freqSlide : Bool := false            -- skydive
  incBy2    : Bool := false
  arpeggio  : Option ArpSpec := none
  pwm       : Option PwmSpec := none
  deriving Repr


def commandoInstruments : List USFInstrument := [
  -- inst 0  (vibrato(depth=2), pwm:bidir(period=0,step=$E0))
  { initCtrl := 0x41,
    initPwLo := 0x00,
    initPwHi := 0x09,
    initAd := 0x29,
    initSr := 0x5F,
    hrCtrl := 0x40,
    vibrato := some { depth := 2 },
    pwm := some { mode := .bidirectional 0x00 0xE0 0x08 0x0E, seedLo := 0x00, seedHi := 0x09 } },
  -- inst 1  (freqSlide, arp(0, 12))
  { initCtrl := 0x41,
    initPwLo := 0x80,
    initPwHi := 0x01,
    initAd := 0x06,
    initSr := 0x4B,
    hrCtrl := 0x40,
    freqSlide := true,
    arpeggio := some { intervals := [0, 12] } },
  -- inst 2  (pwm:linear(speed=$16))
  { initCtrl := 0x41,
    initPwLo := 0x80,
    initPwHi := 0x01,
    initAd := 0x09,
    initSr := 0x9F,
    hrCtrl := 0x40,
    pwm := some { mode := .linear 0x16, seedLo := 0x80, seedHi := 0x01 } },
  -- inst 3  (freqSlide, arp(0, 12))
  { initCtrl := 0x81,
    initPwLo := 0x00,
    initPwHi := 0x02,
    initAd := 0x0A,
    initSr := 0x09,
    hrCtrl := 0x80,
    freqSlide := true,
    arpeggio := some { intervals := [0, 12] } },
  -- inst 4  (freqSlide, incBy2)
  { initCtrl := 0x43,
    initPwLo := 0x00,
    initPwHi := 0x02,
    initAd := 0x0F,
    initSr := 0xC4,
    hrCtrl := 0x42,
    freqSlide := true,
    incBy2 := true },
  -- inst 5  (freqSlide, arp(0, 12), pwm:linear(speed=$02))
  { initCtrl := 0x41,
    initPwLo := 0x80,
    initPwHi := 0x08,
    initAd := 0x05,
    initSr := 0xA9,
    hrCtrl := 0x40,
    freqSlide := true,
    arpeggio := some { intervals := [0, 12] },
    pwm := some { mode := .linear 0x02, seedLo := 0x80, seedHi := 0x08 } },
  -- inst 6  (vibrato(depth=2), pwm:bidir(period=0,step=$E0))
  { initCtrl := 0x41,
    initPwLo := 0x00,
    initPwHi := 0x08,
    initAd := 0x38,
    initSr := 0x7A,
    hrCtrl := 0x40,
    vibrato := some { depth := 2 },
    pwm := some { mode := .bidirectional 0x00 0xE0 0x08 0x0E, seedLo := 0x00, seedHi := 0x08 } },
  -- inst 7  (vibrato(depth=1), freqSlide, arp(0, 12))
  { initCtrl := 0x15,
    initPwLo := 0x80,
    initPwHi := 0x01,
    initAd := 0x0D,
    initSr := 0xFB,
    hrCtrl := 0x14,
    vibrato := some { depth := 1 },
    freqSlide := true,
    arpeggio := some { intervals := [0, 12] } },
  -- inst 8  (vibrato(depth=2), pwm:linear(speed=$03))
  { initCtrl := 0x41,
    initPwLo := 0x00,
    initPwHi := 0x08,
    initAd := 0x49,
    initSr := 0x5B,
    hrCtrl := 0x40,
    vibrato := some { depth := 2 },
    pwm := some { mode := .linear 0x03, seedLo := 0x00, seedHi := 0x08 } },
  -- inst 9  (vibrato(depth=3), freqSlide, arp(0, 12))
  { initCtrl := 0x21,
    initPwLo := 0x00,
    initPwHi := 0x08,
    initAd := 0x04,
    initSr := 0x6F,
    hrCtrl := 0x20,
    vibrato := some { depth := 3 },
    freqSlide := true,
    arpeggio := some { intervals := [0, 12] } },
  -- inst 10  (vibrato(depth=2), freqSlide, arp(0, 12), pwm:linear(speed=$01))
  { initCtrl := 0x41,
    initPwLo := 0x00,
    initPwHi := 0x03,
    initAd := 0x09,
    initSr := 0x6B,
    hrCtrl := 0x40,
    vibrato := some { depth := 2 },
    freqSlide := true,
    arpeggio := some { intervals := [0, 12] },
    pwm := some { mode := .linear 0x01, seedLo := 0x00, seedHi := 0x03 } },
  -- inst 11  (vibrato(depth=1), freqSlide)
  { initCtrl := 0x43,
    initPwLo := 0x00,
    initPwHi := 0x02,
    initAd := 0x07,
    initSr := 0x09,
    hrCtrl := 0x42,
    vibrato := some { depth := 1 },
    freqSlide := true },
  -- inst 12  (freqSlide)
  { initCtrl := 0x41,
    initPwLo := 0x00,
    initPwHi := 0x08,
    initAd := 0x09,
    initSr := 0x0A,
    hrCtrl := 0x40,
    freqSlide := true }
]

end USF2Gen
