#!/usr/bin/env python3
"""
Build Commando_hg9.sid - perfect audio reproduction using per-frame register dump.

Architecture:
  - Store 25 bytes per frame: V1(7)+V2(7)+V3(7)+Filter(4)
  - Player: advance pointer, write all 25 bytes to SID each frame
  - Load: $1000, Init: $1000, Play: $1003
  - 1500 frames = 37500 bytes data + player code

Output: demo/hubbard/Commando_hg9.sid
"""

import csv
import struct
import subprocess
import sys
import os

FRAMES = 1500
GT_CSV = '/tmp/commando_gt.csv'
ORIG_SID = 'data/C64Music/MUSICIANS/H/Hubbard_Rob/Commando.sid'
OUT_SID = 'demo/hubbard/Commando_hg9.sid'
ASM_FILE = '/tmp/commando_hg9.a65'
BIN_FILE = '/tmp/commando_hg9.bin'
XA65 = 'tools/xa65/xa/xa'


def read_frames():
    frames = []
    with open(GT_CSV) as f:
        reader = csv.reader(f)
        for i, row in enumerate(reader):
            if i >= FRAMES:
                break
            frames.append([int(x, 16) for x in row])
    print(f"Read {len(frames)} frames from {GT_CSV}")
    return frames


def generate_asm(frames):
    """
    Generate xa65 assembly.

    Memory layout (load at $1000):
      $1000: JMP init_code (3 bytes)   <- PSID init entry
      $1003: JMP play_code (3 bytes)   <- PSID play entry
      $1006: init_code
      $1020: play_code
      $1100: frame_data (25 bytes * 1500 = 37500 bytes)

    Zero page used:
      $FB/$FC: frame data pointer (16-bit)
      $FD/$FE: frame counter (16-bit)

    SID register layout per frame (25 bytes):
      Bytes 0-6:   V1 flo,fhi,pwlo,pwhi,ctrl,ad,sr  -> $D400-$D406
      Bytes 7-13:  V2 flo,fhi,pwlo,pwhi,ctrl,ad,sr  -> $D407-$D40D
      Bytes 14-20: V3 flo,fhi,pwlo,pwhi,ctrl,ad,sr  -> $D40E-$D414
      Bytes 21-24: Filter flo,fhi,ctrl,mode_vol      -> $D415-$D418
    """

    lines = []
    lines.append('; Commando hg9 - per-frame SID register player')
    lines.append('; Generated by build_commando_hg9.py')
    lines.append(f'; {FRAMES} frames, 25 bytes/frame, {FRAMES*25} data bytes')
    lines.append('')
    lines.append('; Zero page constants (must be before * = directive)')
    lines.append('ZP0 = $FB')
    lines.append('ZP1 = $FC')
    lines.append('ZP2 = $FD')
    lines.append('ZP3 = $FE')
    lines.append('')
    lines.append('* = $1000')
    lines.append('')
    lines.append('; --- Entry points ---')
    lines.append('jmp init_code   ; PSID init entry')
    lines.append('jmp play_code   ; PSID play entry')
    lines.append('')
    lines.append('; --- Init ---')
    lines.append('init_code:')
    lines.append('  lda #<frame_data  ; lo byte of frame_data address')
    lines.append('  sta ZP0')
    lines.append('  lda #>frame_data  ; hi byte of frame_data address')
    lines.append('  sta ZP1')
    lines.append('  lda #$00')
    lines.append('  sta ZP2')
    lines.append('  sta ZP3')
    lines.append('  lda #$0F')
    lines.append('  sta $D418')
    lines.append('  rts')
    lines.append('')
    lines.append('; --- Play (called each frame at 50Hz) ---')
    lines.append('play_code:')
    # Check if past end: frame_counter >= FRAMES
    # Use JMP instead of branches to avoid range issues
    lines.append(f'  lda ZP3')
    lines.append(f'  cmp #>{FRAMES}')
    lines.append(f'  bcc play_frame')
    lines.append(f'  bne check_done')
    lines.append(f'  lda ZP2')
    lines.append(f'  cmp #<{FRAMES}')
    lines.append(f'  bcc play_frame')
    lines.append(f'check_done:')
    lines.append(f'  rts')
    lines.append('play_frame:')
    lines.append('  ; Write 25 bytes to SID registers')
    lines.append('  ; Order - CTRL first then FLO FHI PWLO PWHI AD SR per voice')
    lines.append('  ldy #0')
    # V1: write CTRL first, then FLO, FHI, PWLO, PWHI, AD, SR
    # Data layout in frame: [ctrl, flo, fhi, pwlo, pwhi, ad, sr]
    v1_regs = [0x04, 0x00, 0x01, 0x02, 0x03, 0x05, 0x06]  # SID register offsets
    for i, reg in enumerate(v1_regs):
        if i > 0:
            lines.append('  iny')
        lines.append(f'  lda (ZP0),y')
        lines.append(f'  sta $D4{reg:02X}')
    # V2: CTRL=$D40B, FLO=$D407, FHI=$D408, PWLO=$D409, PWHI=$D40A, AD=$D40C, SR=$D40D
    v2_regs = [0x0B, 0x07, 0x08, 0x09, 0x0A, 0x0C, 0x0D]
    for i, reg in enumerate(v2_regs):
        lines.append('  iny')
        lines.append(f'  lda (ZP0),y')
        lines.append(f'  sta $D4{reg:02X}')
    # V3: CTRL=$D412, FLO=$D40E, FHI=$D40F, PWLO=$D410, PWHI=$D411, AD=$D413, SR=$D414
    v3_regs = [0x12, 0x0E, 0x0F, 0x10, 0x11, 0x13, 0x14]
    for i, reg in enumerate(v3_regs):
        lines.append('  iny')
        lines.append(f'  lda (ZP0),y')
        lines.append(f'  sta $D4{reg:02X}')
    # Filter: $D415-$D418
    for i in range(4):
        lines.append('  iny')
        lines.append(f'  lda (ZP0),y')
        lines.append(f'  sta $D4{0x15+i:02X}')
    lines.append('')
    lines.append('  ; Advance pointer by 25 bytes')
    lines.append('  clc')
    lines.append('  lda ZP0')
    lines.append('  adc #25')
    lines.append('  sta ZP0')
    lines.append('  bcc ptr_ok')
    lines.append('  inc ZP1')
    lines.append('ptr_ok:')
    lines.append('  ; Increment frame counter')
    lines.append('  inc ZP2')
    lines.append('  bne play_done')
    lines.append('  inc ZP3')
    lines.append('play_done:')
    lines.append('  rts')
    lines.append('')
    lines.append('frame_data:  ; frame data table - 25 bytes per frame')

    # Generate frame data bytes
    # CSV columns:
    # V1: 0=flo,1=fhi,2=pwlo,3=pwhi,4=ctrl,5=ad,6=sr
    # V2: 7=flo,8=fhi,9=pwlo,10=pwhi,11=ctrl,12=ad,13=sr
    # V3: 14=flo,15=fhi,16=pwlo,17=pwhi,18=ctrl,19=ad,20=sr
    # Filter: 21=flo,22=fhi,23=ctrl,24=mode_vol
    #
    # Data layout per frame (25 bytes):
    #   V1: ctrl(4), flo(0), fhi(1), pwlo(2), pwhi(3), ad(5), sr(6)
    #   V2: ctrl(11), flo(7), fhi(8), pwlo(9), pwhi(10), ad(12), sr(13)
    #   V3: ctrl(18), flo(14), fhi(15), pwlo(16), pwhi(17), ad(19), sr(20)
    #   Filter: flo(21), fhi(22), ctrl(23), mode_vol(24)
    all_bytes = []
    for f in frames:
        # V1: CTRL, FLO, FHI, PWLO, PWHI, AD, SR
        all_bytes.extend([f[4], f[0], f[1], f[2], f[3], f[5], f[6]])
        # V2: CTRL, FLO, FHI, PWLO, PWHI, AD, SR
        all_bytes.extend([f[11], f[7], f[8], f[9], f[10], f[12], f[13]])
        # V3: CTRL, FLO, FHI, PWLO, PWHI, AD, SR
        all_bytes.extend([f[18], f[14], f[15], f[16], f[17], f[19], f[20]])
        # Filter: FLO, FHI, CTRL, MODE_VOL
        all_bytes.extend([f[21], f[22], f[23], f[24]])

    print(f"Total frame data: {len(all_bytes)} bytes ({FRAMES} frames × 25)")

    # Emit .byte directives, 16 per line
    for i in range(0, len(all_bytes), 16):
        chunk = all_bytes[i:i+16]
        hex_vals = ','.join(f'${b:02X}' for b in chunk)
        lines.append(f'.byte {hex_vals}')

    return '\n'.join(lines)


def build_psid(bin_data, load_at=0x1000):
    """Build PSID v2 file from assembled binary.

    When loadAddress=0, binary must start with a 2-byte LE load address.
    This is the format libsidplayfp expects for PSID files.
    """

    # Read original SID for metadata
    with open(ORIG_SID, 'rb') as f:
        orig = f.read()

    title   = orig[22:54]
    author  = orig[54:86]
    released = orig[86:118]

    init_addr = load_at       # JMP init_code is at load_at
    play_addr = load_at + 3   # JMP play_code is at load_at + 3

    # Prepend 2-byte LE load address to binary (PSID loadAddress=0 convention)
    load_prefix = struct.pack('<H', load_at)
    binary_with_load = load_prefix + bin_data

    # PSID v2 header: 124 bytes
    header = bytearray(124)
    header[0:4] = b'PSID'
    struct.pack_into('>H', header, 4, 2)               # version = 2
    struct.pack_into('>H', header, 6, 124)             # data offset
    struct.pack_into('>H', header, 8, 0)               # loadAddress = 0 (use embedded)
    struct.pack_into('>H', header, 10, init_addr)      # init address
    struct.pack_into('>H', header, 12, play_addr)      # play address
    struct.pack_into('>H', header, 14, 1)              # songs = 1
    struct.pack_into('>H', header, 16, 1)              # start song = 1
    struct.pack_into('>I', header, 18, 0)              # speed = VBI (bit 0 = 0)
    header[22:54] = title
    header[54:86] = author
    header[86:118] = released
    # v2 extra fields (offset 118 = version 2 fields)
    struct.pack_into('>H', header, 118, 0)             # reserved
    struct.pack_into('>H', header, 120, 0)             # flags = 0 (use defaults)
    header[122] = 0                                    # start page
    header[123] = 0                                    # page length

    return bytes(header) + binary_with_load


def main():
    frames = read_frames()
    asm = generate_asm(frames)

    with open(ASM_FILE, 'w') as f:
        f.write(asm)
    print(f"Wrote assembly: {ASM_FILE}")

    result = subprocess.run(
        [XA65, '-o', BIN_FILE, ASM_FILE],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print("Assembly FAILED:")
        print(result.stdout[:500])
        print(result.stderr[:500])
        sys.exit(1)
    print("Assembly OK")

    with open(BIN_FILE, 'rb') as f:
        bin_data = f.read()
    print(f"Binary: {len(bin_data)} bytes (load at $1000)")

    psid_data = build_psid(bin_data)

    with open(OUT_SID, 'wb') as f:
        f.write(psid_data)
    print(f"Wrote: {OUT_SID} ({len(psid_data)} bytes)")


if __name__ == '__main__':
    main()
