#!/usr/bin/env python3
"""
Build Commando frame codebook player (hg15).

Per-voice split codebook strategy:
  V1: freq_cb(flo,fhi) [56] + timb_cb(pwlo,pwhi,ctrl,ad,sr) [35]
      streams: v1_freq_stream, v1_timb_stream  (1500 bytes each)
  V2: full_cb(flo,fhi,pwlo,pwhi,ctrl,ad,sr) [56]
      stream:  v2_stream (1500 bytes)
  V3: freq_cb(flo,fhi) [15] + raw pwlo stream + timb_cb(pwhi,ctrl,ad,sr) [5]
      streams: v3_freq_stream, v3_pwlo_stream (raw), v3_timb_stream (1500 each)
  Filter: constant registers (hardcoded in init)

All codebooks <= 256 entries → 1-byte index, LDA table,X addressing.
Total data: ~9.7KB for 30 seconds of perfect audio.

Output: demo/hubbard/Commando_hg15.s
        demo/hubbard/Commando_hg15.sid
"""

import subprocess
import sys
import os
import struct

SIDDUMP = '/home/jtr/sidfinity/tools/siddump'
COMMANDO = '/home/jtr/sidfinity/data/C64Music/MUSICIANS/H/Hubbard_Rob/Commando.sid'
XA65 = '/home/jtr/sidfinity/tools/xa65/xa/xa'
OUTDIR = '/home/jtr/sidfinity/demo/hubbard'
ASM_OUT = os.path.join(OUTDIR, 'Commando_hg15.s')
SID_OUT = os.path.join(OUTDIR, 'Commando_hg15.sid')
OBJ_OUT = '/tmp/commando_hg15.o'

DURATION_SECS = 30  # 30s * 50fps = 1500 frames


def capture_frames():
    """Run siddump and return list of 25-int tuples."""
    result = subprocess.run(
        [SIDDUMP, COMMANDO, '--duration', str(DURATION_SECS)],
        capture_output=True, text=True
    )
    lines = result.stdout.strip().split('\n')
    frames = []
    data_started = False
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if line.startswith('{'):
            continue
        if line.startswith('V1_FREQ'):
            data_started = True
            continue
        if data_started:
            vals = [int(x, 16) for x in line.split(',')]
            assert len(vals) == 25, f"Expected 25 columns, got {len(vals)}"
            frames.append(vals)
    print(f"Captured {len(frames)} frames")
    return frames


def build_codebook(frames, cols):
    """Return (codebook_list_of_tuples, stream_list_of_indices)."""
    seen = {}
    codebook = []
    stream = []
    for frame in frames:
        key = tuple(frame[c] for c in cols)
        if key not in seen:
            seen[key] = len(codebook)
            codebook.append(key)
        stream.append(seen[key])
    return codebook, stream


def bytes_hex(data, cols=16, indent='        '):
    """Format bytes as .byte lines."""
    lines = []
    for i in range(0, len(data), cols):
        chunk = data[i:i + cols]
        lines.append(indent + '.byte ' + ','.join(f'${x:02X}' for x in chunk))
    return '\n'.join(lines)


def emit_cb_arrays(label_prefix, codebook, field_names):
    """
    Emit parallel arrays: label_prefix_field0, label_prefix_field1, ...
    Each array has one byte per codebook entry.
    """
    parts = []
    for fi, fname in enumerate(field_names):
        parts.append(f'{label_prefix}_{fname}:')
        data = [entry[fi] for entry in codebook]
        parts.append(bytes_hex(data))
    return '\n'.join(parts)


def generate_asm(frames,
                 v1_freq_cb, v1_freq_stream,
                 v1_timb_cb, v1_timb_stream,
                 v2_cb, v2_stream,
                 v3_freq_cb, v3_freq_stream,
                 v3_pwlo_stream,
                 v3_timb_cb, v3_timb_stream,
                 fl_const):
    """Generate the complete 6502 assembly."""
    n = len(frames)

    print(f"  V1 freq_cb: {len(v1_freq_cb)} entries")
    print(f"  V1 timb_cb: {len(v1_timb_cb)} entries")
    print(f"  V2 full_cb: {len(v2_cb)} entries")
    print(f"  V3 freq_cb: {len(v3_freq_cb)} entries")
    print(f"  V3 timb_cb: {len(v3_timb_cb)} entries")
    print(f"  Filter: {fl_const} (hardcoded)")
    print(f"  Frames:  {n}")

    for name, cb in [('V1_freq', v1_freq_cb), ('V1_timb', v1_timb_cb),
                     ('V2', v2_cb), ('V3_freq', v3_freq_cb), ('V3_timb', v3_timb_cb)]:
        if len(cb) > 256:
            raise ValueError(f"{name} codebook has {len(cb)} entries, exceeds 256!")

    # ZP usage:
    #   $80/$81 = frame counter lo/hi
    #   $82/$83 = v1_freq_ptr lo/hi
    #   $84/$85 = v1_timb_ptr lo/hi
    #   $86/$87 = v2_ptr lo/hi
    #   $88/$89 = v3_freq_ptr lo/hi
    #   $8A/$8B = v3_pwlo_ptr lo/hi
    #   $8C/$8D = v3_timb_ptr lo/hi

    L = []  # assembly lines

    def e(s=''):
        L.append(s)

    e('; Commando frame codebook player (hg15)')
    e('; Auto-generated by build_commando_codebook.py')
    e(f'; {n} frames at 50fps = {n//50}s, V1={len(v1_freq_cb)}f/{len(v1_timb_cb)}t '
      f'V2={len(v2_cb)} V3={len(v3_freq_cb)}f/{len(v3_timb_cb)}t')
    e()
    e('        * = $1000')
    e('        jmp init')
    e('        jmp play')
    e()

    # INIT
    e('init')
    e('        ; Hardcode filter registers (constant throughout)')
    e(f'        lda #${fl_const[0]:02X}')
    e('        sta $D415')
    e(f'        lda #${fl_const[1]:02X}')
    e('        sta $D416')
    e(f'        lda #${fl_const[2]:02X}')
    e('        sta $D417')
    e(f'        lda #${fl_const[3]:02X}')
    e('        sta $D418')
    e()
    e('        ; Reset frame counter')
    e('        lda #0')
    e('        sta $80')
    e('        sta $81')
    e()
    e('        ; Set stream pointers')
    e('        lda #<v1_freq_stream')
    e('        sta $82')
    e('        lda #>v1_freq_stream')
    e('        sta $83')
    e('        lda #<v1_timb_stream')
    e('        sta $84')
    e('        lda #>v1_timb_stream')
    e('        sta $85')
    e('        lda #<v2_stream')
    e('        sta $86')
    e('        lda #>v2_stream')
    e('        sta $87')
    e('        lda #<v3_freq_stream')
    e('        sta $88')
    e('        lda #>v3_freq_stream')
    e('        sta $89')
    e('        lda #<v3_pwlo_stream')
    e('        sta $8A')
    e('        lda #>v3_pwlo_stream')
    e('        sta $8B')
    e('        lda #<v3_timb_stream')
    e('        sta $8C')
    e('        lda #>v3_timb_stream')
    e('        sta $8D')
    e('        rts')
    e()

    # Helper: emit code to read one index from a stream and advance pointer
    # Returns the X register loaded with the codebook index
    def emit_read_stream(ptr_lo, ptr_hi, next_label):
        lines = [
            f'        ldy #0',
            f'        lda ({ptr_lo}),y',
            f'        tax',
            f'        inc {ptr_lo}',
            f'        bne {next_label}',
            f'        inc {ptr_hi}',
            f'{next_label}',
        ]
        return '\n'.join(lines)

    # Helper: read raw byte from stream (no X, just A)
    def emit_read_raw(ptr_lo, ptr_hi, next_label):
        lines = [
            f'        ldy #0',
            f'        lda ({ptr_lo}),y',
            f'        inc {ptr_lo}',
            f'        bne {next_label}',
            f'        inc {ptr_hi}',
            f'{next_label}',
        ]
        return '\n'.join(lines)

    # PLAY
    e('play')
    e('        ; Check end of stream (frame >= N)')
    e(f'        lda $80')
    e(f'        cmp #<{n}')
    e(f'        lda $81')
    e(f'        sbc #>{n}')
    e(f'        bcc play_body')
    e(f'        rts')
    e(f'play_body')
    e()

    # Voice 1: freq + timbral
    e('        ; --- Voice 1 ---')
    e('        ; Read freq index')
    e(emit_read_stream('$82', '$83', 'v1f_nc'))
    e('        ; Lookup V1 freq registers')
    e('        lda v1f_flo,x')
    e('        sta $D400')
    e('        lda v1f_fhi,x')
    e('        sta $D401')
    e()
    e('        ; Read timbral index')
    e(emit_read_stream('$84', '$85', 'v1t_nc'))
    e('        ; Lookup V1 timbral registers')
    e('        lda v1t_pwlo,x')
    e('        sta $D402')
    e('        lda v1t_pwhi,x')
    e('        sta $D403')
    e('        lda v1t_ctrl,x')
    e('        sta $D404')
    e('        lda v1t_ad,x')
    e('        sta $D405')
    e('        lda v1t_sr,x')
    e('        sta $D406')
    e()

    # Voice 2: full 7-tuple
    e('        ; --- Voice 2 ---')
    e(emit_read_stream('$86', '$87', 'v2_nc'))
    e('        lda v2_flo,x')
    e('        sta $D407')
    e('        lda v2_fhi,x')
    e('        sta $D408')
    e('        lda v2_pwlo,x')
    e('        sta $D409')
    e('        lda v2_pwhi,x')
    e('        sta $D40A')
    e('        lda v2_ctrl,x')
    e('        sta $D40B')
    e('        lda v2_ad,x')
    e('        sta $D40C')
    e('        lda v2_sr,x')
    e('        sta $D40D')
    e()

    # Voice 3: freq + raw pwlo + timbral
    e('        ; --- Voice 3 ---')
    e('        ; Read freq index')
    e(emit_read_stream('$88', '$89', 'v3f_nc'))
    e('        lda v3f_flo,x')
    e('        sta $D40E')
    e('        lda v3f_fhi,x')
    e('        sta $D40F')
    e()
    e('        ; Read raw pwlo byte')
    e(emit_read_raw('$8A', '$8B', 'v3p_nc'))
    e('        sta $D410')
    e()
    e('        ; Read timbral index')
    e(emit_read_stream('$8C', '$8D', 'v3t_nc'))
    e('        lda v3t_pwhi,x')
    e('        sta $D411')
    e('        lda v3t_ctrl,x')
    e('        sta $D412')
    e('        lda v3t_ad,x')
    e('        sta $D413')
    e('        lda v3t_sr,x')
    e('        sta $D414')
    e()

    # Advance frame counter
    e('        ; Advance frame counter')
    e('        inc $80')
    e('        bne play_nc')
    e('        inc $81')
    e('play_nc')
    e('        rts')
    e()

    # DATA SECTION
    e('; ============================================================')
    e('; Codebook parallel arrays')
    e('; ============================================================')
    e()
    e('; --- V1 frequency codebook (flo, fhi) ---')
    e(emit_cb_arrays('v1f', v1_freq_cb, ['flo', 'fhi']))
    e()
    e('; --- V1 timbral codebook (pwlo, pwhi, ctrl, ad, sr) ---')
    e(emit_cb_arrays('v1t', v1_timb_cb, ['pwlo', 'pwhi', 'ctrl', 'ad', 'sr']))
    e()
    e('; --- V2 full codebook (flo, fhi, pwlo, pwhi, ctrl, ad, sr) ---')
    e(emit_cb_arrays('v2', v2_cb, ['flo', 'fhi', 'pwlo', 'pwhi', 'ctrl', 'ad', 'sr']))
    e()
    e('; --- V3 frequency codebook (flo, fhi) ---')
    e(emit_cb_arrays('v3f', v3_freq_cb, ['flo', 'fhi']))
    e()
    e('; --- V3 timbral codebook (pwhi, ctrl, ad, sr) ---')
    e(emit_cb_arrays('v3t', v3_timb_cb, ['pwhi', 'ctrl', 'ad', 'sr']))
    e()
    e('; ============================================================')
    e('; Stream data (1 byte per frame = codebook index)')
    e('; ============================================================')
    e()
    e('v1_freq_stream:')
    e(bytes_hex(v1_freq_stream))
    e()
    e('v1_timb_stream:')
    e(bytes_hex(v1_timb_stream))
    e()
    e('v2_stream:')
    e(bytes_hex(v2_stream))
    e()
    e('v3_freq_stream:')
    e(bytes_hex(v3_freq_stream))
    e()
    e('v3_pwlo_stream:')
    e(bytes_hex(v3_pwlo_stream))
    e()
    e('v3_timb_stream:')
    e(bytes_hex(v3_timb_stream))
    e()

    return '\n'.join(L)


def build_psid(prg_data, load_addr, init_addr, play_addr, title, author, released):
    """Build PSID v2."""
    def padded(s, n):
        return s.encode('ascii', errors='replace')[:n].ljust(n, b'\x00')

    header = (
        b'PSID' +
        struct.pack('>H', 2) +          # version
        struct.pack('>H', 0x7C) +       # data offset (124 = v2 header)
        struct.pack('>H', 0) +          # load address = 0 (read from data section)
        struct.pack('>H', init_addr) +
        struct.pack('>H', play_addr) +
        struct.pack('>H', 1) +          # songs
        struct.pack('>H', 1) +          # start song
        struct.pack('>I', 1) +          # speed (bit 0 = 50Hz VBI)
        padded(title, 32) +
        padded(author, 32) +
        padded(released, 32) +
        struct.pack('>H', 0) +          # flags
        b'\x00' +                       # start page
        b'\x00' +                       # page length
        struct.pack('>H', 0)            # reserved
    )
    assert len(header) == 0x7C, f"Header length {len(header)} != 124"

    # PSID body: 2-byte load address (LE) + code
    body = struct.pack('<H', load_addr) + prg_data
    return header + body


def main():
    print("=== Step 1: Capture ground truth ===")
    frames = capture_frames()
    n = len(frames)

    print("\n=== Step 2: Build codebooks ===")
    # V1: cols 0-6 (flo,fhi,pwlo,pwhi,ctrl,ad,sr)
    v1_freq_cb, v1_freq_stream = build_codebook(frames, [0, 1])
    v1_timb_cb, v1_timb_stream = build_codebook(frames, [2, 3, 4, 5, 6])

    # V2: cols 7-13
    v2_cb, v2_stream = build_codebook(frames, list(range(7, 14)))

    # V3: cols 14-20 (flo,fhi,pwlo,pwhi,ctrl,ad,sr)
    # split: freq=(14,15), pwlo=16 raw, timb=(17,18,19,20)
    v3_freq_cb, v3_freq_stream = build_codebook(frames, [14, 15])
    v3_pwlo_stream = [f[16] for f in frames]
    v3_timb_cb, v3_timb_stream = build_codebook(frames, [17, 18, 19, 20])

    # Filter: cols 21-24 — check if constant
    fl_vals = [tuple(f[21:25]) for f in frames]
    fl_unique = set(fl_vals)
    if len(fl_unique) == 1:
        fl_const = list(fl_unique)[0]
        print(f"  Filter is constant: {[f'${x:02X}' for x in fl_const]}")
    else:
        print(f"  Filter has {len(fl_unique)} unique values — using first as constant")
        fl_const = fl_vals[0]

    total_cb = (len(v1_freq_cb) * 2 + len(v1_timb_cb) * 5 +
                len(v2_cb) * 7 +
                len(v3_freq_cb) * 2 + len(v3_timb_cb) * 4)
    total_streams = n * 6  # 6 streams of n bytes each (v3_pwlo is raw)
    print(f"\n  Codebook total: {total_cb} bytes")
    print(f"  Stream total:   {total_streams} bytes")
    print(f"  Grand total:    {total_cb + total_streams} bytes (vs {n*25} bytes raw)")

    print("\n=== Step 3: Generate assembly ===")
    asm_src = generate_asm(
        frames,
        v1_freq_cb, v1_freq_stream,
        v1_timb_cb, v1_timb_stream,
        v2_cb, v2_stream,
        v3_freq_cb, v3_freq_stream,
        v3_pwlo_stream,
        v3_timb_cb, v3_timb_stream,
        fl_const
    )

    with open(ASM_OUT, 'w') as f:
        f.write(asm_src)
    print(f"  Written: {ASM_OUT} ({os.path.getsize(ASM_OUT)} bytes)")

    print("\n=== Step 4: Assemble with xa65 ===")
    result = subprocess.run(
        [XA65, '-o', OBJ_OUT, ASM_OUT],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print("ASSEMBLER ERROR:")
        print(result.stdout)
        print(result.stderr)
        sys.exit(1)
    print(f"  Assembled OK: {OBJ_OUT}")

    print("\n=== Step 5: Build PSID ===")
    with open(OBJ_OUT, 'rb') as f:
        prg_data = f.read()

    # xa65 outputs raw binary at the assembled address (no 2-byte load prefix)
    # The assembly starts with: JMP init_addr (4C lo hi), JMP play_addr (4C lo hi)
    load_addr = 0x1000
    init_addr = prg_data[1] | (prg_data[2] << 8)
    play_addr = prg_data[4] | (prg_data[5] << 8)

    print(f"  Load: ${load_addr:04X}  Init: ${init_addr:04X}  Play: ${play_addr:04X}")
    print(f"  PRG size: {len(prg_data)} bytes")

    psid = build_psid(
        prg_data, load_addr, init_addr, play_addr,
        'Commando (hg15 codebook)',
        'Rob Hubbard',
        '1985 Elite / SIDfinity hg15'
    )
    with open(SID_OUT, 'wb') as f:
        f.write(psid)
    print(f"  Written: {SID_OUT} ({len(psid)} bytes)")

    print("\n=== Step 6: Sanity check ===")
    # Verify first 5 frames reconstruct correctly
    ok = True
    for i in range(min(5, n)):
        # V1 freq
        fi = v1_freq_stream[i]
        flo_got = v1_freq_cb[fi][0]
        fhi_got = v1_freq_cb[fi][1]
        flo_want = frames[i][0]
        fhi_want = frames[i][1]
        if flo_got != flo_want or fhi_got != fhi_want:
            print(f"  MISMATCH frame {i} V1 freq: got ${flo_got:02X}${fhi_got:02X} want ${flo_want:02X}${fhi_want:02X}")
            ok = False
        # V3 pwlo
        pwlo_got = v3_pwlo_stream[i]
        pwlo_want = frames[i][16]
        if pwlo_got != pwlo_want:
            print(f"  MISMATCH frame {i} V3 pwlo: got ${pwlo_got:02X} want ${pwlo_want:02X}")
            ok = False
    if ok:
        print("  First 5 frames verify OK")

    print(f"\nDone.")
    print(f"  Assembly: {ASM_OUT}")
    print(f"  SID file: {SID_OUT}")


if __name__ == '__main__':
    main()
