#!/usr/bin/env python3
"""
Commando codebook player generator.

Approach:
- Capture 1500 frames of ground truth (25 regs per frame)
- For each voice (7 regs) + filter/vol (4 regs), find common 7-byte tuples
- Build a 240-entry codebook for each voice channel
- IDs 0..239 = codebook lookup
- ID 254 ($FE) = end of stream (loop)
- ID 255 ($FF) = inline (raw bytes follow)
- Per voice, store a stream of IDs

SID CSV column order per voice:
  cols 0-6:   V1: freq_lo, freq_hi, pw_lo, pw_hi, ctrl, ad, sr
  cols 7-13:  V2: ...
  cols 14-20: V3: ...
  cols 21-24: FILT: lo, hi, ctrl, mode_vol

SID register map (natural order = CSV order):
  V1: $D400=freq_lo, $D401=freq_hi, $D402=pw_lo, $D403=pw_hi, $D404=ctrl, $D405=ad, $D406=sr
  V2: $D407-$D40D (same pattern)
  V3: $D40E-$D414 (same pattern)
  Filter: $D415=filt_lo, $D416=filt_hi, $D417=filt_ctrl, $D418=mode_vol
"""

import sys
import os
from collections import Counter

FRAMES_CSV = '/tmp/commando_frames.csv'
OUT_ASM    = '/home/jtr/sidfinity/demo/hubbard/Commando_hg14.s'
OUT_SID    = '/home/jtr/sidfinity/demo/hubbard/Commando_hg14.sid'

CODEBOOK_SIZE = 240
INLINE_ID     = 0xFF  # signals raw bytes follow in stream
END_ID        = 0xFE  # signals end of stream (player loops)


# ---------------------------------------------------------------------------
def load_frames(path):
    frames = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            vals = [int(x, 16) for x in line.split(',')]
            assert len(vals) == 25, f"Expected 25 columns, got {len(vals)}"
            frames.append(vals)
    return frames


def build_codebook(tuples_list, max_entries=CODEBOOK_SIZE):
    counter = Counter(tuples_list)
    top = [t for t, _ in counter.most_common(max_entries)]
    return top


def encode_stream(tuples_list, codebook):
    """
    Returns (stream_bytes, inline_count).
    stream_bytes: list of ints
      - single ID byte if tuple in codebook
      - INLINE_ID followed by raw tuple bytes if not in codebook
    Does NOT include END_ID - caller appends it.
    """
    cb_map = {t: i for i, t in enumerate(codebook)}
    stream = []
    inline_count = 0
    for t in tuples_list:
        if t in cb_map:
            stream.append(cb_map[t])
        else:
            stream.append(INLINE_ID)
            stream.extend(list(t))
            inline_count += 1
    stream.append(END_ID)
    return stream, inline_count


# ---------------------------------------------------------------------------
def asm_stream(data, label):
    lines = [f"{label}"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_str = ','.join(f'${b:02X}' for b in chunk)
        lines.append(f"        .byte {hex_str}")
    return '\n'.join(lines)


def asm_codebook(cb, label, tsize):
    """Emit codebook as flat byte array (CODEBOOK_SIZE * tsize bytes)."""
    flat = []
    for t in cb:
        flat.extend(list(t))
    # Pad to CODEBOOK_SIZE entries
    while len(flat) < CODEBOOK_SIZE * tsize:
        flat.append(0)
    lines = [f"{label}"]
    for i in range(0, len(flat), 16):
        chunk = flat[i:i + 16]
        hex_str = ','.join(f'${b:02X}' for b in chunk)
        lines.append(f"        .byte {hex_str}")
    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# 6502 assembly template
# Zero-page layout:
#   $70/$71 = V1 stream ptr
#   $72/$73 = V2 stream ptr
#   $74/$75 = V3 stream ptr
#   $76/$77 = FV stream ptr
#   $78     = saved ID
#   $7B/$7C = scratch 16-bit ptr (codebook entry addr)
#
# Codebook lookup for 7-byte entries:
#   offset = ID * 7 = ID * 8 - ID  (using 3x ASL then subtract)
#   ptr = codebook_vN + offset
#
# Codebook lookup for 4-byte entries:
#   offset = ID * 4  (2x ASL, 16-bit)
#   ptr = codebook_fv + offset

PLAYER_TEMPLATE = """; Commando codebook player - Generated by commando_codebook.py
; {nframes} frames codebook size {cb_size}

        * = $1000
        jmp init
        jmp play

; INIT
init
        lda #<stream_v1
        sta $70
        lda #>stream_v1
        sta $71
        lda #<stream_v2
        sta $72
        lda #>stream_v2
        sta $73
        lda #<stream_v3
        sta $74
        lda #>stream_v3
        sta $75
        lda #<stream_fv
        sta $76
        lda #>stream_fv
        sta $77
        lda #$0F
        sta $D418
        rts

; PLAY - called once per frame at 50Hz
play
        jsr do_voice1
        jsr do_voice2
        jsr do_voice3
        jsr do_filtervol
        rts

; MUL7 helper - Input A = ID 0..239, Output $7B/$7C = ID*7
mul7
        sta $78
        sta $7B
        lda #0
        sta $7C
        asl $7B
        rol $7C
        asl $7B
        rol $7C
        asl $7B
        rol $7C             ; = ID * 8
        sec
        lda $7B
        sbc $78
        sta $7B
        lda $7C
        sbc #0
        sta $7C             ; = ID * 7
        rts

; VOICE 1 - D400=fl D401=fh D402=pwl D403=pwh D404=ctrl D405=ad D406=sr
do_voice1
        ldy #0
        lda ($70),y         ; read ID byte
        cmp #$FE            ; end?
        bne v1_notend
        lda #<stream_v1     ; reset to start (loop)
        sta $70
        lda #>stream_v1
        sta $71
        lda ($70),y
v1_notend
        cmp #$FF            ; inline?
        beq v1_inline
        ; lookup
        jsr mul7
        clc
        lda $7B
        adc #<codebook_v1
        sta $7B
        lda $7C
        adc #>codebook_v1
        sta $7C
        jsr inc70           ; advance stream
        ldy #0
        lda ($7B),y
        sta $D400
        iny
        lda ($7B),y
        sta $D401
        iny
        lda ($7B),y
        sta $D402
        iny
        lda ($7B),y
        sta $D403
        iny
        lda ($7B),y
        sta $D404
        iny
        lda ($7B),y
        sta $D405
        iny
        lda ($7B),y
        sta $D406
        rts
v1_inline
        jsr inc70           ; skip INLINE_ID
        ldy #0
        lda ($70),y
        sta $D400
        jsr inc70
        ldy #0
        lda ($70),y
        sta $D401
        jsr inc70
        ldy #0
        lda ($70),y
        sta $D402
        jsr inc70
        ldy #0
        lda ($70),y
        sta $D403
        jsr inc70
        ldy #0
        lda ($70),y
        sta $D404
        jsr inc70
        ldy #0
        lda ($70),y
        sta $D405
        jsr inc70
        ldy #0
        lda ($70),y
        sta $D406
        jsr inc70
        rts

; VOICE 2 - D407=fl D408=fh D409=pwl D40A=pwh D40B=ctrl D40C=ad D40D=sr
do_voice2
        ldy #0
        lda ($72),y
        cmp #$FE
        bne v2_notend
        lda #<stream_v2
        sta $72
        lda #>stream_v2
        sta $73
        lda ($72),y
v2_notend
        cmp #$FF
        beq v2_inline
        jsr mul7
        clc
        lda $7B
        adc #<codebook_v2
        sta $7B
        lda $7C
        adc #>codebook_v2
        sta $7C
        jsr inc72
        ldy #0
        lda ($7B),y
        sta $D407
        iny
        lda ($7B),y
        sta $D408
        iny
        lda ($7B),y
        sta $D409
        iny
        lda ($7B),y
        sta $D40A
        iny
        lda ($7B),y
        sta $D40B
        iny
        lda ($7B),y
        sta $D40C
        iny
        lda ($7B),y
        sta $D40D
        rts
v2_inline
        jsr inc72
        ldy #0
        lda ($72),y
        sta $D407
        jsr inc72
        ldy #0
        lda ($72),y
        sta $D408
        jsr inc72
        ldy #0
        lda ($72),y
        sta $D409
        jsr inc72
        ldy #0
        lda ($72),y
        sta $D40A
        jsr inc72
        ldy #0
        lda ($72),y
        sta $D40B
        jsr inc72
        ldy #0
        lda ($72),y
        sta $D40C
        jsr inc72
        ldy #0
        lda ($72),y
        sta $D40D
        jsr inc72
        rts

; VOICE 3 - D40E=fl D40F=fh D410=pwl D411=pwh D412=ctrl D413=ad D414=sr
do_voice3
        ldy #0
        lda ($74),y
        cmp #$FE
        bne v3_notend
        lda #<stream_v3
        sta $74
        lda #>stream_v3
        sta $75
        lda ($74),y
v3_notend
        cmp #$FF
        beq v3_inline
        jsr mul7
        clc
        lda $7B
        adc #<codebook_v3
        sta $7B
        lda $7C
        adc #>codebook_v3
        sta $7C
        jsr inc74
        ldy #0
        lda ($7B),y
        sta $D40E
        iny
        lda ($7B),y
        sta $D40F
        iny
        lda ($7B),y
        sta $D410
        iny
        lda ($7B),y
        sta $D411
        iny
        lda ($7B),y
        sta $D412
        iny
        lda ($7B),y
        sta $D413
        iny
        lda ($7B),y
        sta $D414
        rts
v3_inline
        jsr inc74
        ldy #0
        lda ($74),y
        sta $D40E
        jsr inc74
        ldy #0
        lda ($74),y
        sta $D40F
        jsr inc74
        ldy #0
        lda ($74),y
        sta $D410
        jsr inc74
        ldy #0
        lda ($74),y
        sta $D411
        jsr inc74
        ldy #0
        lda ($74),y
        sta $D412
        jsr inc74
        ldy #0
        lda ($74),y
        sta $D413
        jsr inc74
        ldy #0
        lda ($74),y
        sta $D414
        jsr inc74
        rts

; FILTER/VOLUME - D415=filt_lo D416=filt_hi D417=filt_ctrl D418=mode_vol
; Codebook entries 4 bytes, offset = ID*4
do_filtervol
        ldy #0
        lda ($76),y
        cmp #$FE
        bne fv_notend
        lda #<stream_fv
        sta $76
        lda #>stream_fv
        sta $77
        lda ($76),y
fv_notend
        cmp #$FF
        beq fv_inline
        ; ID * 4 (2x ASL, 16-bit)
        sta $7B
        lda #0
        sta $7C
        asl $7B
        rol $7C
        asl $7B
        rol $7C
        clc
        lda $7B
        adc #<codebook_fv
        sta $7B
        lda $7C
        adc #>codebook_fv
        sta $7C
        jsr inc76
        ldy #0
        lda ($7B),y
        sta $D415
        iny
        lda ($7B),y
        sta $D416
        iny
        lda ($7B),y
        sta $D417
        iny
        lda ($7B),y
        sta $D418
        rts
fv_inline
        jsr inc76
        ldy #0
        lda ($76),y
        sta $D415
        jsr inc76
        ldy #0
        lda ($76),y
        sta $D416
        jsr inc76
        ldy #0
        lda ($76),y
        sta $D417
        jsr inc76
        ldy #0
        lda ($76),y
        sta $D418
        jsr inc76
        rts

; POINTER INCREMENT HELPERS
inc70
        inc $70
        bne inc70_done
        inc $71
inc70_done
        rts

inc72
        inc $72
        bne inc72_done
        inc $73
inc72_done
        rts

inc74
        inc $74
        bne inc74_done
        inc $75
inc74_done
        rts

inc76
        inc $76
        bne inc76_done
        inc $77
inc76_done
        rts

"""


def generate_asm(cb_v1, cb_v2, cb_v3, cb_fv, s_v1, s_v2, s_v3, s_fv, nframes):
    sv1, sv2, sv3, sfv = len(s_v1), len(s_v2), len(s_v3), len(s_fv)
    cbv  = CODEBOOK_SIZE * 7 * 3
    cbfv = CODEBOOK_SIZE * 4
    total = sv1 + sv2 + sv3 + sfv + cbv + cbfv
    orig  = nframes * 25

    header = PLAYER_TEMPLATE.format(
        nframes=nframes, cb_size=CODEBOOK_SIZE,
        sv1=sv1, sv2=sv2, sv3=sv3, sfv=sfv,
        cbv=cbv, cbfv=cbfv, total=total, orig=orig,
        pct=total * 100 // orig,
    )

    parts = [header]
    parts.append('; ===== CODEBOOKS =====')
    parts.append(asm_codebook(cb_v1, 'codebook_v1', 7))
    parts.append(asm_codebook(cb_v2, 'codebook_v2', 7))
    parts.append(asm_codebook(cb_v3, 'codebook_v3', 7))
    parts.append(asm_codebook(cb_fv, 'codebook_fv', 4))
    parts.append('')
    parts.append('; ===== STREAMS =====')
    parts.append(asm_stream(s_v1, 'stream_v1'))
    parts.append(asm_stream(s_v2, 'stream_v2'))
    parts.append(asm_stream(s_v3, 'stream_v3'))
    parts.append(asm_stream(s_fv, 'stream_fv'))
    parts.append('')
    return '\n'.join(parts)


def main():
    print("Loading frames...")
    frames = load_frames(FRAMES_CSV)
    print(f"  {len(frames)} frames loaded")

    v1_tuples = [tuple(f[0:7])   for f in frames]
    v2_tuples = [tuple(f[7:14])  for f in frames]
    v3_tuples = [tuple(f[14:21]) for f in frames]
    fv_tuples = [tuple(f[21:25]) for f in frames]

    print("Building codebooks...")
    cb_v1 = build_codebook(v1_tuples)
    cb_v2 = build_codebook(v2_tuples)
    cb_v3 = build_codebook(v3_tuples)
    cb_fv = build_codebook(fv_tuples)

    print(f"  V1: {len(cb_v1)} entries (top freq={Counter(v1_tuples).most_common(1)[0][1]})")
    print(f"  V2: {len(cb_v2)} entries")
    print(f"  V3: {len(cb_v3)} entries")
    print(f"  FV: {len(cb_fv)} entries")

    print("Encoding streams...")
    s_v1, il1 = encode_stream(v1_tuples, cb_v1)
    s_v2, il2 = encode_stream(v2_tuples, cb_v2)
    s_v3, il3 = encode_stream(v3_tuples, cb_v3)
    s_fv, il4 = encode_stream(fv_tuples, cb_fv)

    print(f"  V1: {len(s_v1)}B  {il1} inlines")
    print(f"  V2: {len(s_v2)}B  {il2} inlines")
    print(f"  V3: {len(s_v3)}B  {il3} inlines")
    print(f"  FV: {len(s_fv)}B  {il4} inlines")

    orig  = len(frames) * 25
    total = (len(s_v1) + len(s_v2) + len(s_v3) + len(s_fv)
             + CODEBOOK_SIZE * 7 * 3 + CODEBOOK_SIZE * 4)
    print(f"\nCompression: {orig} -> {total} bytes ({total*100//orig}%)")

    print("\nGenerating assembly...")
    asm = generate_asm(cb_v1, cb_v2, cb_v3, cb_fv, s_v1, s_v2, s_v3, s_fv, len(frames))

    os.makedirs(os.path.dirname(OUT_ASM), exist_ok=True)
    with open(OUT_ASM, 'w') as f:
        f.write(asm)
    print(f"  Written: {OUT_ASM}")

    return cb_v1, cb_v2, cb_v3, cb_fv, s_v1, s_v2, s_v3, s_fv, frames


def build_psid(prg_path, out_path, load_addr=0x1000, init_addr=0x1000, play_addr=0x1003):
    """Wrap a raw PRG in a PSID v2 header."""
    import struct

    with open(prg_path, 'rb') as f:
        prg_data = f.read()

    hdr = bytearray(124)
    hdr[0:4] = b'PSID'
    struct.pack_into('>H', hdr, 4, 2)
    struct.pack_into('>H', hdr, 6, 0x7C)
    struct.pack_into('>H', hdr, 8, 0x0000)   # load addr embedded in data
    struct.pack_into('>H', hdr, 10, init_addr)
    struct.pack_into('>H', hdr, 12, play_addr)
    struct.pack_into('>H', hdr, 14, 1)        # 1 song
    struct.pack_into('>H', hdr, 16, 1)        # default song 1
    struct.pack_into('>I', hdr, 18, 0)        # speed: VBI

    title    = b'Commando (codebook)'
    author   = b'Rob Hubbard'
    released = b'1985 Elite / SIDfinity codebook'
    hdr[22:22+min(32,len(title))]    = title[:32]
    hdr[54:54+min(32,len(author))]   = author[:32]
    hdr[86:86+min(32,len(released))] = released[:32]
    struct.pack_into('>H', hdr, 118, 0x0002)  # PAL flag

    prg_with_addr = struct.pack('<H', load_addr) + prg_data
    out = bytes(hdr) + prg_with_addr

    with open(out_path, 'wb') as f:
        f.write(out)
    return len(out)


if __name__ == '__main__':
    main()

    # Assemble
    import subprocess
    prg_out = OUT_ASM.replace('.s', '.prg')
    prg_out = '/tmp/commando_hg14.prg'
    r = subprocess.run(
        ['tools/xa65/xa/xa', '-o', prg_out, OUT_ASM],
        capture_output=True, text=True
    )
    if r.returncode != 0:
        print(f"ASSEMBLE ERROR:\n{r.stderr}")
        sys.exit(1)
    print(f"Assembled: {prg_out}")

    # Build PSID
    size = build_psid(prg_out, OUT_SID)
    print(f"PSID: {OUT_SID} ({size} bytes)")

    # Verify with siddump
    r = subprocess.run(['tools/siddump', OUT_SID], capture_output=True, text=True)
    first_frame = r.stdout.strip().split('\n')[2]
    expected_first = '58,AF,80,01,15,0D,FB,00,00,00,02,43,0F,C4,A9,03,80,01,41,09,9F,00,00,00,0F'
    if first_frame == expected_first:
        print("First frame: MATCH")
    else:
        print(f"First frame MISMATCH:\n  Got:      {first_frame}\n  Expected: {expected_first}")

    print("Done.")
